// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_summaries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const closeDailySummary = `-- name: CloseDailySummary :execresult
UPDATE daily_summaries
SET status = 'closed', closed_at = ?, updated_at = CURRENT_TIMESTAMP(3)
WHERE organization_id = ? AND id = ? AND status IN ('draft', 'published')
`

type CloseDailySummaryParams struct {
	ClosedAt       sql.NullTime `json:"closed_at"`
	OrganizationID uint64       `json:"organization_id"`
	ID             uint64       `json:"id"`
}

func (q *Queries) CloseDailySummary(ctx context.Context, arg CloseDailySummaryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, closeDailySummary, arg.ClosedAt, arg.OrganizationID, arg.ID)
}

const correctDailySummary = `-- name: CorrectDailySummary :execresult
UPDATE daily_summaries
SET content = ?, child_updates_json = ?, current_version = current_version + 1,
    status = 'published', published_at = ?, closed_at = NULL, withdrawn_at = NULL,
    withdrawal_reason = '', correction_reason = ?,
    created_by_user_id = ?, created_by_name = ?, updated_at = CURRENT_TIMESTAMP(3)
WHERE organization_id = ? AND id = ? AND status IN ('published', 'closed', 'withdrawn')
`

type CorrectDailySummaryParams struct {
	Content          string        `json:"content"`
	ChildUpdatesJson string        `json:"child_updates_json"`
	PublishedAt      sql.NullTime  `json:"published_at"`
	CorrectionReason string        `json:"correction_reason"`
	CreatedByUserID  sql.NullInt64 `json:"created_by_user_id"`
	CreatedByName    string        `json:"created_by_name"`
	OrganizationID   uint64        `json:"organization_id"`
	ID               uint64        `json:"id"`
}

func (q *Queries) CorrectDailySummary(ctx context.Context, arg CorrectDailySummaryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, correctDailySummary,
		arg.Content,
		arg.ChildUpdatesJson,
		arg.PublishedAt,
		arg.CorrectionReason,
		arg.CreatedByUserID,
		arg.CreatedByName,
		arg.OrganizationID,
		arg.ID,
	)
}

const createDailySummary = `-- name: CreateDailySummary :execresult
INSERT INTO daily_summaries (organization_id, summary_date, content, child_updates_json, status, created_by_user_id, created_by_name, generated_at)
VALUES (?, ?, ?, ?, 'draft', ?, ?, ?)
`

type CreateDailySummaryParams struct {
	OrganizationID   uint64        `json:"organization_id"`
	SummaryDate      time.Time     `json:"summary_date"`
	Content          string        `json:"content"`
	ChildUpdatesJson string        `json:"child_updates_json"`
	CreatedByUserID  sql.NullInt64 `json:"created_by_user_id"`
	CreatedByName    string        `json:"created_by_name"`
	GeneratedAt      sql.NullTime  `json:"generated_at"`
}

func (q *Queries) CreateDailySummary(ctx context.Context, arg CreateDailySummaryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDailySummary,
		arg.OrganizationID,
		arg.SummaryDate,
		arg.Content,
		arg.ChildUpdatesJson,
		arg.CreatedByUserID,
		arg.CreatedByName,
		arg.GeneratedAt,
	)
}

const createDailySummaryVersion = `-- name: CreateDailySummaryVersion :exec
INSERT INTO daily_summary_versions (
    organization_id, daily_summary_id, version, action, content, child_updates_json,
    reason, created_by_user_id, created_by_name, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDailySummaryVersionParams struct {
	OrganizationID   uint64        `json:"organization_id"`
	DailySummaryID   uint64        `json:"daily_summary_id"`
	Version          uint32        `json:"version"`
	Action           string        `json:"action"`
	Content          string        `json:"content"`
	ChildUpdatesJson string        `json:"child_updates_json"`
	Reason           string        `json:"reason"`
	CreatedByUserID  sql.NullInt64 `json:"created_by_user_id"`
	CreatedByName    string        `json:"created_by_name"`
	CreatedAt        time.Time     `json:"created_at"`
}

func (q *Queries) CreateDailySummaryVersion(ctx context.Context, arg CreateDailySummaryVersionParams) error {
	_, err := q.db.ExecContext(ctx, createDailySummaryVersion,
		arg.OrganizationID,
		arg.DailySummaryID,
		arg.Version,
		arg.Action,
		arg.Content,
		arg.ChildUpdatesJson,
		arg.Reason,
		arg.CreatedByUserID,
		arg.CreatedByName,
		arg.CreatedAt,
	)
	return err
}

const getDailySummaryByDate = `-- name: GetDailySummaryByDate :one
SELECT id, organization_id, summary_date, content, child_updates_json, status, current_version,
       created_by_user_id, created_by_name, generated_at, published_at, closed_at,
       withdrawn_at, withdrawal_reason, correction_reason, created_at, updated_at
FROM daily_summaries WHERE organization_id = ? AND summary_date = ? LIMIT 1
`

type GetDailySummaryByDateParams struct {
	OrganizationID uint64    `json:"organization_id"`
	SummaryDate    time.Time `json:"summary_date"`
}

type GetDailySummaryByDateRow struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	SummaryDate      time.Time     `json:"summary_date"`
	Content          string        `json:"content"`
	ChildUpdatesJson string        `json:"child_updates_json"`
	Status           string        `json:"status"`
	CurrentVersion   uint32        `json:"current_version"`
	CreatedByUserID  sql.NullInt64 `json:"created_by_user_id"`
	CreatedByName    string        `json:"created_by_name"`
	GeneratedAt      sql.NullTime  `json:"generated_at"`
	PublishedAt      sql.NullTime  `json:"published_at"`
	ClosedAt         sql.NullTime  `json:"closed_at"`
	WithdrawnAt      sql.NullTime  `json:"withdrawn_at"`
	WithdrawalReason string        `json:"withdrawal_reason"`
	CorrectionReason string        `json:"correction_reason"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

func (q *Queries) GetDailySummaryByDate(ctx context.Context, arg GetDailySummaryByDateParams) (GetDailySummaryByDateRow, error) {
	row := q.db.QueryRowContext(ctx, getDailySummaryByDate, arg.OrganizationID, arg.SummaryDate)
	var i GetDailySummaryByDateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SummaryDate,
		&i.Content,
		&i.ChildUpdatesJson,
		&i.Status,
		&i.CurrentVersion,
		&i.CreatedByUserID,
		&i.CreatedByName,
		&i.GeneratedAt,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.WithdrawnAt,
		&i.WithdrawalReason,
		&i.CorrectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailySummaryByID = `-- name: GetDailySummaryByID :one
SELECT id, organization_id, summary_date, content, child_updates_json, status, current_version,
       created_by_user_id, created_by_name, generated_at, published_at, closed_at,
       withdrawn_at, withdrawal_reason, correction_reason, created_at, updated_at
FROM daily_summaries WHERE organization_id = ? AND id = ? LIMIT 1
`

type GetDailySummaryByIDParams struct {
	OrganizationID uint64 `json:"organization_id"`
	ID             uint64 `json:"id"`
}

type GetDailySummaryByIDRow struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	SummaryDate      time.Time     `json:"summary_date"`
	Content          string        `json:"content"`
	ChildUpdatesJson string        `json:"child_updates_json"`
	Status           string        `json:"status"`
	CurrentVersion   uint32        `json:"current_version"`
	CreatedByUserID  sql.NullInt64 `json:"created_by_user_id"`
	CreatedByName    string        `json:"created_by_name"`
	GeneratedAt      sql.NullTime  `json:"generated_at"`
	PublishedAt      sql.NullTime  `json:"published_at"`
	ClosedAt         sql.NullTime  `json:"closed_at"`
	WithdrawnAt      sql.NullTime  `json:"withdrawn_at"`
	WithdrawalReason string        `json:"withdrawal_reason"`
	CorrectionReason string        `json:"correction_reason"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

func (q *Queries) GetDailySummaryByID(ctx context.Context, arg GetDailySummaryByIDParams) (GetDailySummaryByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDailySummaryByID, arg.OrganizationID, arg.ID)
	var i GetDailySummaryByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SummaryDate,
		&i.Content,
		&i.ChildUpdatesJson,
		&i.Status,
		&i.CurrentVersion,
		&i.CreatedByUserID,
		&i.CreatedByName,
		&i.GeneratedAt,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.WithdrawnAt,
		&i.WithdrawalReason,
		&i.CorrectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailySummaryReadAt = `-- name: GetDailySummaryReadAt :one
SELECT r.read_version, r.read_at, s.current_version
FROM daily_summary_reads r
JOIN daily_summaries s ON s.id = r.daily_summary_id AND s.organization_id = r.organization_id
WHERE r.organization_id = ? AND r.daily_summary_id = ? AND r.parent_account_id = ?
LIMIT 1
`

type GetDailySummaryReadAtParams struct {
	OrganizationID  uint64 `json:"organization_id"`
	DailySummaryID  uint64 `json:"daily_summary_id"`
	ParentAccountID uint64 `json:"parent_account_id"`
}

type GetDailySummaryReadAtRow struct {
	ReadVersion    uint32    `json:"read_version"`
	ReadAt         time.Time `json:"read_at"`
	CurrentVersion uint32    `json:"current_version"`
}

func (q *Queries) GetDailySummaryReadAt(ctx context.Context, arg GetDailySummaryReadAtParams) (GetDailySummaryReadAtRow, error) {
	row := q.db.QueryRowContext(ctx, getDailySummaryReadAt, arg.OrganizationID, arg.DailySummaryID, arg.ParentAccountID)
	var i GetDailySummaryReadAtRow
	err := row.Scan(&i.ReadVersion, &i.ReadAt, &i.CurrentVersion)
	return i, err
}

const listDailySummaries = `-- name: ListDailySummaries :many
SELECT id, organization_id, summary_date, content, child_updates_json, status, current_version,
       created_by_user_id, created_by_name, generated_at, published_at, closed_at,
       withdrawn_at, withdrawal_reason, correction_reason, created_at, updated_at
FROM daily_summaries
WHERE organization_id = ? AND (? IS NULL OR summary_date = ?)
ORDER BY summary_date DESC, id DESC
`

type ListDailySummariesParams struct {
	OrganizationID    uint64       `json:"organization_id"`
	SummaryDateFilter sql.NullTime `json:"summary_date_filter"`
}

type ListDailySummariesRow struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	SummaryDate      time.Time     `json:"summary_date"`
	Content          string        `json:"content"`
	ChildUpdatesJson string        `json:"child_updates_json"`
	Status           string        `json:"status"`
	CurrentVersion   uint32        `json:"current_version"`
	CreatedByUserID  sql.NullInt64 `json:"created_by_user_id"`
	CreatedByName    string        `json:"created_by_name"`
	GeneratedAt      sql.NullTime  `json:"generated_at"`
	PublishedAt      sql.NullTime  `json:"published_at"`
	ClosedAt         sql.NullTime  `json:"closed_at"`
	WithdrawnAt      sql.NullTime  `json:"withdrawn_at"`
	WithdrawalReason string        `json:"withdrawal_reason"`
	CorrectionReason string        `json:"correction_reason"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

func (q *Queries) ListDailySummaries(ctx context.Context, arg ListDailySummariesParams) ([]ListDailySummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailySummaries, arg.OrganizationID, arg.SummaryDateFilter, arg.SummaryDateFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailySummariesRow{}
	for rows.Next() {
		var i ListDailySummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SummaryDate,
			&i.Content,
			&i.ChildUpdatesJson,
			&i.Status,
			&i.CurrentVersion,
			&i.CreatedByUserID,
			&i.CreatedByName,
			&i.GeneratedAt,
			&i.PublishedAt,
			&i.ClosedAt,
			&i.WithdrawnAt,
			&i.WithdrawalReason,
			&i.CorrectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailySummaryVersions = `-- name: ListDailySummaryVersions :many
SELECT id, organization_id, daily_summary_id, version, action, content, child_updates_json,
       reason, created_by_user_id, created_by_name, created_at
FROM daily_summary_versions
WHERE organization_id = ? AND daily_summary_id = ?
ORDER BY version DESC, id DESC
`

type ListDailySummaryVersionsParams struct {
	OrganizationID uint64 `json:"organization_id"`
	DailySummaryID uint64 `json:"daily_summary_id"`
}

func (q *Queries) ListDailySummaryVersions(ctx context.Context, arg ListDailySummaryVersionsParams) ([]DailySummaryVersion, error) {
	rows, err := q.db.QueryContext(ctx, listDailySummaryVersions, arg.OrganizationID, arg.DailySummaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailySummaryVersion{}
	for rows.Next() {
		var i DailySummaryVersion
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DailySummaryID,
			&i.Version,
			&i.Action,
			&i.Content,
			&i.ChildUpdatesJson,
			&i.Reason,
			&i.CreatedByUserID,
			&i.CreatedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDailySummaryRead = `-- name: MarkDailySummaryRead :exec
INSERT INTO daily_summary_reads (organization_id, daily_summary_id, parent_account_id, read_version, read_at)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE read_version = VALUES(read_version), read_at = VALUES(read_at)
`

type MarkDailySummaryReadParams struct {
	OrganizationID  uint64    `json:"organization_id"`
	DailySummaryID  uint64    `json:"daily_summary_id"`
	ParentAccountID uint64    `json:"parent_account_id"`
	ReadVersion     uint32    `json:"read_version"`
	ReadAt          time.Time `json:"read_at"`
}

func (q *Queries) MarkDailySummaryRead(ctx context.Context, arg MarkDailySummaryReadParams) error {
	_, err := q.db.ExecContext(ctx, markDailySummaryRead,
		arg.OrganizationID,
		arg.DailySummaryID,
		arg.ParentAccountID,
		arg.ReadVersion,
		arg.ReadAt,
	)
	return err
}

const publishDailySummary = `-- name: PublishDailySummary :execresult
UPDATE daily_summaries
SET status = 'published', published_at = ?, updated_at = CURRENT_TIMESTAMP(3)
WHERE organization_id = ? AND id = ? AND status = 'draft'
`

type PublishDailySummaryParams struct {
	PublishedAt    sql.NullTime `json:"published_at"`
	OrganizationID uint64       `json:"organization_id"`
	ID             uint64       `json:"id"`
}

func (q *Queries) PublishDailySummary(ctx context.Context, arg PublishDailySummaryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, publishDailySummary, arg.PublishedAt, arg.OrganizationID, arg.ID)
}

const updateDailySummary = `-- name: UpdateDailySummary :execresult
UPDATE daily_summaries
SET content = ?, child_updates_json = ?, current_version = current_version + 1, updated_at = CURRENT_TIMESTAMP(3)
WHERE organization_id = ? AND id = ? AND status = 'draft'
`

type UpdateDailySummaryParams struct {
	Content          string `json:"content"`
	ChildUpdatesJson string `json:"child_updates_json"`
	OrganizationID   uint64 `json:"organization_id"`
	ID               uint64 `json:"id"`
}

func (q *Queries) UpdateDailySummary(ctx context.Context, arg UpdateDailySummaryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateDailySummary,
		arg.Content,
		arg.ChildUpdatesJson,
		arg.OrganizationID,
		arg.ID,
	)
}

const withdrawDailySummary = `-- name: WithdrawDailySummary :execresult
UPDATE daily_summaries
SET status = 'withdrawn', withdrawn_at = ?, withdrawal_reason = ?, updated_at = CURRENT_TIMESTAMP(3)
WHERE organization_id = ? AND id = ? AND status = 'published'
`

type WithdrawDailySummaryParams struct {
	WithdrawnAt      sql.NullTime `json:"withdrawn_at"`
	WithdrawalReason string       `json:"withdrawal_reason"`
	OrganizationID   uint64       `json:"organization_id"`
	ID               uint64       `json:"id"`
}

func (q *Queries) WithdrawDailySummary(ctx context.Context, arg WithdrawDailySummaryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, withdrawDailySummary,
		arg.WithdrawnAt,
		arg.WithdrawalReason,
		arg.OrganizationID,
		arg.ID,
	)
}
