// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: homework.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createHomeworkTask = `-- name: CreateHomeworkTask :execresult
INSERT INTO homework_tasks (
    organization_id, homework_date, school_id, school_class_id,
    subject, content, attachment_urls, created_by_user_id, creator_name, status
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'active')
`

type CreateHomeworkTaskParams struct {
	OrganizationID  uint64          `json:"organization_id"`
	HomeworkDate    time.Time       `json:"homework_date"`
	SchoolID        uint64          `json:"school_id"`
	SchoolClassID   uint64          `json:"school_class_id"`
	Subject         string          `json:"subject"`
	Content         string          `json:"content"`
	AttachmentUrls  json.RawMessage `json:"attachment_urls"`
	CreatedByUserID sql.NullInt64   `json:"created_by_user_id"`
	CreatorName     string          `json:"creator_name"`
}

func (q *Queries) CreateHomeworkTask(ctx context.Context, arg CreateHomeworkTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createHomeworkTask,
		arg.OrganizationID,
		arg.HomeworkDate,
		arg.SchoolID,
		arg.SchoolClassID,
		arg.Subject,
		arg.Content,
		arg.AttachmentUrls,
		arg.CreatedByUserID,
		arg.CreatorName,
	)
}

const createHomeworkTaskStudent = `-- name: CreateHomeworkTaskStudent :execresult
INSERT INTO homework_task_students (organization_id, task_id, student_id, status)
VALUES (?, ?, ?, 'pending')
`

type CreateHomeworkTaskStudentParams struct {
	OrganizationID uint64 `json:"organization_id"`
	TaskID         uint64 `json:"task_id"`
	StudentID      uint64 `json:"student_id"`
}

func (q *Queries) CreateHomeworkTaskStudent(ctx context.Context, arg CreateHomeworkTaskStudentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createHomeworkTaskStudent, arg.OrganizationID, arg.TaskID, arg.StudentID)
}

const getHomeworkTask = `-- name: GetHomeworkTask :one
SELECT id, organization_id, homework_date, school_id, school_class_id,
       subject, content, attachment_urls, created_by_user_id, creator_name, status,
       created_at, updated_at
FROM homework_tasks
WHERE id = ? AND organization_id = ?
LIMIT 1
`

type GetHomeworkTaskParams struct {
	ID             uint64 `json:"id"`
	OrganizationID uint64 `json:"organization_id"`
}

type GetHomeworkTaskRow struct {
	ID              uint64          `json:"id"`
	OrganizationID  uint64          `json:"organization_id"`
	HomeworkDate    time.Time       `json:"homework_date"`
	SchoolID        uint64          `json:"school_id"`
	SchoolClassID   uint64          `json:"school_class_id"`
	Subject         string          `json:"subject"`
	Content         string          `json:"content"`
	AttachmentUrls  json.RawMessage `json:"attachment_urls"`
	CreatedByUserID sql.NullInt64   `json:"created_by_user_id"`
	CreatorName     string          `json:"creator_name"`
	Status          string          `json:"status"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

func (q *Queries) GetHomeworkTask(ctx context.Context, arg GetHomeworkTaskParams) (GetHomeworkTaskRow, error) {
	row := q.db.QueryRowContext(ctx, getHomeworkTask, arg.ID, arg.OrganizationID)
	var i GetHomeworkTaskRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.HomeworkDate,
		&i.SchoolID,
		&i.SchoolClassID,
		&i.Subject,
		&i.Content,
		&i.AttachmentUrls,
		&i.CreatedByUserID,
		&i.CreatorName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHomeworkTaskStudent = `-- name: GetHomeworkTaskStudent :one
SELECT hs.id AS homework_task_student_id, hs.organization_id, hs.task_id,
       hs.student_id, s.name AS student_name, hs.status, hs.correction_note,
       hs.reviewed_by_user_id, hs.reviewed_at, hs.created_at, hs.updated_at
FROM homework_task_students hs
JOIN students s ON s.id = hs.student_id
WHERE hs.task_id = ? AND hs.student_id = ? AND hs.organization_id = ?
LIMIT 1
`

type GetHomeworkTaskStudentParams struct {
	TaskID         uint64 `json:"task_id"`
	StudentID      uint64 `json:"student_id"`
	OrganizationID uint64 `json:"organization_id"`
}

type GetHomeworkTaskStudentRow struct {
	HomeworkTaskStudentID uint64        `json:"homework_task_student_id"`
	OrganizationID        uint64        `json:"organization_id"`
	TaskID                uint64        `json:"task_id"`
	StudentID             uint64        `json:"student_id"`
	StudentName           string        `json:"student_name"`
	Status                string        `json:"status"`
	CorrectionNote        string        `json:"correction_note"`
	ReviewedByUserID      sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt            sql.NullTime  `json:"reviewed_at"`
	CreatedAt             time.Time     `json:"created_at"`
	UpdatedAt             time.Time     `json:"updated_at"`
}

func (q *Queries) GetHomeworkTaskStudent(ctx context.Context, arg GetHomeworkTaskStudentParams) (GetHomeworkTaskStudentRow, error) {
	row := q.db.QueryRowContext(ctx, getHomeworkTaskStudent, arg.TaskID, arg.StudentID, arg.OrganizationID)
	var i GetHomeworkTaskStudentRow
	err := row.Scan(
		&i.HomeworkTaskStudentID,
		&i.OrganizationID,
		&i.TaskID,
		&i.StudentID,
		&i.StudentName,
		&i.Status,
		&i.CorrectionNote,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHomeworkTaskStudents = `-- name: ListHomeworkTaskStudents :many
SELECT hs.id AS homework_task_student_id, hs.organization_id, hs.task_id,
       hs.student_id, s.name AS student_name, hs.status, hs.correction_note,
       hs.reviewed_by_user_id, hs.reviewed_at, hs.created_at, hs.updated_at
FROM homework_task_students hs
JOIN students s ON s.id = hs.student_id
WHERE hs.task_id = ? AND hs.organization_id = ?
ORDER BY s.name, hs.student_id
`

type ListHomeworkTaskStudentsParams struct {
	TaskID         uint64 `json:"task_id"`
	OrganizationID uint64 `json:"organization_id"`
}

type ListHomeworkTaskStudentsRow struct {
	HomeworkTaskStudentID uint64        `json:"homework_task_student_id"`
	OrganizationID        uint64        `json:"organization_id"`
	TaskID                uint64        `json:"task_id"`
	StudentID             uint64        `json:"student_id"`
	StudentName           string        `json:"student_name"`
	Status                string        `json:"status"`
	CorrectionNote        string        `json:"correction_note"`
	ReviewedByUserID      sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt            sql.NullTime  `json:"reviewed_at"`
	CreatedAt             time.Time     `json:"created_at"`
	UpdatedAt             time.Time     `json:"updated_at"`
}

func (q *Queries) ListHomeworkTaskStudents(ctx context.Context, arg ListHomeworkTaskStudentsParams) ([]ListHomeworkTaskStudentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listHomeworkTaskStudents, arg.TaskID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeworkTaskStudentsRow{}
	for rows.Next() {
		var i ListHomeworkTaskStudentsRow
		if err := rows.Scan(
			&i.HomeworkTaskStudentID,
			&i.OrganizationID,
			&i.TaskID,
			&i.StudentID,
			&i.StudentName,
			&i.Status,
			&i.CorrectionNote,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeworkTasks = `-- name: ListHomeworkTasks :many
SELECT id, organization_id, homework_date, school_id, school_class_id,
       subject, content, attachment_urls, created_by_user_id, creator_name, status,
       created_at, updated_at
FROM homework_tasks
WHERE organization_id = ?
ORDER BY homework_date DESC, id DESC
`

type ListHomeworkTasksRow struct {
	ID              uint64          `json:"id"`
	OrganizationID  uint64          `json:"organization_id"`
	HomeworkDate    time.Time       `json:"homework_date"`
	SchoolID        uint64          `json:"school_id"`
	SchoolClassID   uint64          `json:"school_class_id"`
	Subject         string          `json:"subject"`
	Content         string          `json:"content"`
	AttachmentUrls  json.RawMessage `json:"attachment_urls"`
	CreatedByUserID sql.NullInt64   `json:"created_by_user_id"`
	CreatorName     string          `json:"creator_name"`
	Status          string          `json:"status"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

func (q *Queries) ListHomeworkTasks(ctx context.Context, organizationID uint64) ([]ListHomeworkTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listHomeworkTasks, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeworkTasksRow{}
	for rows.Next() {
		var i ListHomeworkTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.HomeworkDate,
			&i.SchoolID,
			&i.SchoolClassID,
			&i.Subject,
			&i.Content,
			&i.AttachmentUrls,
			&i.CreatedByUserID,
			&i.CreatorName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentHomework = `-- name: ListStudentHomework :many
SELECT t.id AS task_id, t.organization_id, t.homework_date, t.school_id,
       t.school_class_id, t.subject, t.content, t.attachment_urls, t.created_by_user_id,
       t.creator_name, t.status AS task_status, t.created_at AS task_created_at,
       t.updated_at AS task_updated_at, hs.id AS homework_task_student_id,
       hs.student_id, s.name AS student_name, hs.status AS student_status,
       hs.correction_note, hs.reviewed_by_user_id, hs.reviewed_at,
       hs.created_at AS student_created_at, hs.updated_at AS student_updated_at
FROM homework_task_students hs
JOIN homework_tasks t ON t.id = hs.task_id
JOIN students s ON s.id = hs.student_id
WHERE hs.organization_id = ? AND hs.student_id = ? AND t.status = 'active'
ORDER BY t.homework_date DESC, t.id DESC
`

type ListStudentHomeworkParams struct {
	OrganizationID uint64 `json:"organization_id"`
	StudentID      uint64 `json:"student_id"`
}

type ListStudentHomeworkRow struct {
	TaskID                uint64          `json:"task_id"`
	OrganizationID        uint64          `json:"organization_id"`
	HomeworkDate          time.Time       `json:"homework_date"`
	SchoolID              uint64          `json:"school_id"`
	SchoolClassID         uint64          `json:"school_class_id"`
	Subject               string          `json:"subject"`
	Content               string          `json:"content"`
	AttachmentUrls        json.RawMessage `json:"attachment_urls"`
	CreatedByUserID       sql.NullInt64   `json:"created_by_user_id"`
	CreatorName           string          `json:"creator_name"`
	TaskStatus            string          `json:"task_status"`
	TaskCreatedAt         time.Time       `json:"task_created_at"`
	TaskUpdatedAt         time.Time       `json:"task_updated_at"`
	HomeworkTaskStudentID uint64          `json:"homework_task_student_id"`
	StudentID             uint64          `json:"student_id"`
	StudentName           string          `json:"student_name"`
	StudentStatus         string          `json:"student_status"`
	CorrectionNote        string          `json:"correction_note"`
	ReviewedByUserID      sql.NullInt64   `json:"reviewed_by_user_id"`
	ReviewedAt            sql.NullTime    `json:"reviewed_at"`
	StudentCreatedAt      time.Time       `json:"student_created_at"`
	StudentUpdatedAt      time.Time       `json:"student_updated_at"`
}

func (q *Queries) ListStudentHomework(ctx context.Context, arg ListStudentHomeworkParams) ([]ListStudentHomeworkRow, error) {
	rows, err := q.db.QueryContext(ctx, listStudentHomework, arg.OrganizationID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentHomeworkRow{}
	for rows.Next() {
		var i ListStudentHomeworkRow
		if err := rows.Scan(
			&i.TaskID,
			&i.OrganizationID,
			&i.HomeworkDate,
			&i.SchoolID,
			&i.SchoolClassID,
			&i.Subject,
			&i.Content,
			&i.AttachmentUrls,
			&i.CreatedByUserID,
			&i.CreatorName,
			&i.TaskStatus,
			&i.TaskCreatedAt,
			&i.TaskUpdatedAt,
			&i.HomeworkTaskStudentID,
			&i.StudentID,
			&i.StudentName,
			&i.StudentStatus,
			&i.CorrectionNote,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.StudentCreatedAt,
			&i.StudentUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHomeworkTaskStudentReview = `-- name: UpdateHomeworkTaskStudentReview :execresult
UPDATE homework_task_students
SET status = ?, correction_note = ?, reviewed_by_user_id = ?, reviewed_at = ?
WHERE task_id = ? AND student_id = ? AND organization_id = ?
`

type UpdateHomeworkTaskStudentReviewParams struct {
	Status           string        `json:"status"`
	CorrectionNote   string        `json:"correction_note"`
	ReviewedByUserID sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt       sql.NullTime  `json:"reviewed_at"`
	TaskID           uint64        `json:"task_id"`
	StudentID        uint64        `json:"student_id"`
	OrganizationID   uint64        `json:"organization_id"`
}

func (q *Queries) UpdateHomeworkTaskStudentReview(ctx context.Context, arg UpdateHomeworkTaskStudentReviewParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateHomeworkTaskStudentReview,
		arg.Status,
		arg.CorrectionNote,
		arg.ReviewedByUserID,
		arg.ReviewedAt,
		arg.TaskID,
		arg.StudentID,
		arg.OrganizationID,
	)
}
