// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: master_data.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createAcademicTerm = `-- name: CreateAcademicTerm :execresult
INSERT INTO academic_terms (organization_id, name, starts_on, ends_on, is_current, status)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAcademicTermParams struct {
	OrganizationID uint64    `json:"organization_id"`
	Name           string    `json:"name"`
	StartsOn       time.Time `json:"starts_on"`
	EndsOn         time.Time `json:"ends_on"`
	IsCurrent      bool      `json:"is_current"`
	Status         string    `json:"status"`
}

func (q *Queries) CreateAcademicTerm(ctx context.Context, arg CreateAcademicTermParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAcademicTerm,
		arg.OrganizationID,
		arg.Name,
		arg.StartsOn,
		arg.EndsOn,
		arg.IsCurrent,
		arg.Status,
	)
}

const createCareClass = `-- name: CreateCareClass :execresult
INSERT INTO care_classes (organization_id, name, capacity, status)
VALUES (?, ?, ?, ?)
`

type CreateCareClassParams struct {
	OrganizationID uint64 `json:"organization_id"`
	Name           string `json:"name"`
	Capacity       uint32 `json:"capacity"`
	Status         string `json:"status"`
}

func (q *Queries) CreateCareClass(ctx context.Context, arg CreateCareClassParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCareClass,
		arg.OrganizationID,
		arg.Name,
		arg.Capacity,
		arg.Status,
	)
}

const createSchool = `-- name: CreateSchool :execresult
INSERT INTO schools (organization_id, name, address, contact_phone, status)
VALUES (?, ?, ?, ?, ?)
`

type CreateSchoolParams struct {
	OrganizationID uint64 `json:"organization_id"`
	Name           string `json:"name"`
	Address        string `json:"address"`
	ContactPhone   string `json:"contact_phone"`
	Status         string `json:"status"`
}

func (q *Queries) CreateSchool(ctx context.Context, arg CreateSchoolParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSchool,
		arg.OrganizationID,
		arg.Name,
		arg.Address,
		arg.ContactPhone,
		arg.Status,
	)
}

const createSchoolClass = `-- name: CreateSchoolClass :execresult
INSERT INTO school_classes (organization_id, school_id, term_id, grade, name, status)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSchoolClassParams struct {
	OrganizationID uint64 `json:"organization_id"`
	SchoolID       uint64 `json:"school_id"`
	TermID         uint64 `json:"term_id"`
	Grade          string `json:"grade"`
	Name           string `json:"name"`
	Status         string `json:"status"`
}

func (q *Queries) CreateSchoolClass(ctx context.Context, arg CreateSchoolClassParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSchoolClass,
		arg.OrganizationID,
		arg.SchoolID,
		arg.TermID,
		arg.Grade,
		arg.Name,
		arg.Status,
	)
}

const createStudent = `-- name: CreateStudent :execresult
INSERT INTO students (
    organization_id, school_id, term_id, school_class_id, care_class_id,
    name, gender, birth_date, student_no, guardian_phone, emergency_contact,
    emergency_phone, status, notes
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateStudentParams struct {
	OrganizationID   uint64        `json:"organization_id"`
	SchoolID         uint64        `json:"school_id"`
	TermID           uint64        `json:"term_id"`
	SchoolClassID    uint64        `json:"school_class_id"`
	CareClassID      sql.NullInt64 `json:"care_class_id"`
	Name             string        `json:"name"`
	Gender           string        `json:"gender"`
	BirthDate        sql.NullTime  `json:"birth_date"`
	StudentNo        string        `json:"student_no"`
	GuardianPhone    string        `json:"guardian_phone"`
	EmergencyContact string        `json:"emergency_contact"`
	EmergencyPhone   string        `json:"emergency_phone"`
	Status           string        `json:"status"`
	Notes            string        `json:"notes"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createStudent,
		arg.OrganizationID,
		arg.SchoolID,
		arg.TermID,
		arg.SchoolClassID,
		arg.CareClassID,
		arg.Name,
		arg.Gender,
		arg.BirthDate,
		arg.StudentNo,
		arg.GuardianPhone,
		arg.EmergencyContact,
		arg.EmergencyPhone,
		arg.Status,
		arg.Notes,
	)
}

const getSchoolByID = `-- name: GetSchoolByID :one
SELECT id, organization_id, name, address, contact_phone, status, created_at, updated_at
FROM schools
WHERE id = ? AND organization_id = ?
LIMIT 1
`

type GetSchoolByIDParams struct {
	ID             uint64 `json:"id"`
	OrganizationID uint64 `json:"organization_id"`
}

func (q *Queries) GetSchoolByID(ctx context.Context, arg GetSchoolByIDParams) (School, error) {
	row := q.db.QueryRowContext(ctx, getSchoolByID, arg.ID, arg.OrganizationID)
	var i School
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Address,
		&i.ContactPhone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, organization_id, school_id, term_id, school_class_id, care_class_id,
       name, gender, birth_date, student_no, guardian_phone, emergency_contact,
       emergency_phone, status, notes, created_at, updated_at
FROM students
WHERE id = ? AND organization_id = ?
LIMIT 1
`

type GetStudentByIDParams struct {
	ID             uint64 `json:"id"`
	OrganizationID uint64 `json:"organization_id"`
}

func (q *Queries) GetStudentByID(ctx context.Context, arg GetStudentByIDParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByID, arg.ID, arg.OrganizationID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SchoolID,
		&i.TermID,
		&i.SchoolClassID,
		&i.CareClassID,
		&i.Name,
		&i.Gender,
		&i.BirthDate,
		&i.StudentNo,
		&i.GuardianPhone,
		&i.EmergencyContact,
		&i.EmergencyPhone,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAcademicTerms = `-- name: ListAcademicTerms :many
SELECT id, organization_id, name, starts_on, ends_on, is_current, status, created_at, updated_at
FROM academic_terms
WHERE organization_id = ?
ORDER BY starts_on DESC, id DESC
`

func (q *Queries) ListAcademicTerms(ctx context.Context, organizationID uint64) ([]AcademicTerm, error) {
	rows, err := q.db.QueryContext(ctx, listAcademicTerms, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcademicTerm{}
	for rows.Next() {
		var i AcademicTerm
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.StartsOn,
			&i.EndsOn,
			&i.IsCurrent,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCareClasses = `-- name: ListCareClasses :many
SELECT id, organization_id, name, capacity, status, created_at, updated_at
FROM care_classes
WHERE organization_id = ?
ORDER BY name, id
`

func (q *Queries) ListCareClasses(ctx context.Context, organizationID uint64) ([]CareClass, error) {
	rows, err := q.db.QueryContext(ctx, listCareClasses, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CareClass{}
	for rows.Next() {
		var i CareClass
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolClasses = `-- name: ListSchoolClasses :many
SELECT id, organization_id, school_id, term_id, grade, name, status, created_at, updated_at
FROM school_classes
WHERE organization_id = ?
ORDER BY school_id, term_id, grade, name, id
`

func (q *Queries) ListSchoolClasses(ctx context.Context, organizationID uint64) ([]SchoolClass, error) {
	rows, err := q.db.QueryContext(ctx, listSchoolClasses, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchoolClass{}
	for rows.Next() {
		var i SchoolClass
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SchoolID,
			&i.TermID,
			&i.Grade,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchools = `-- name: ListSchools :many
SELECT id, organization_id, name, address, contact_phone, status, created_at, updated_at
FROM schools
WHERE organization_id = ?
ORDER BY name, id
`

func (q *Queries) ListSchools(ctx context.Context, organizationID uint64) ([]School, error) {
	rows, err := q.db.QueryContext(ctx, listSchools, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Address,
			&i.ContactPhone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudents = `-- name: ListStudents :many
SELECT id, organization_id, school_id, term_id, school_class_id, care_class_id,
       name, gender, birth_date, student_no, guardian_phone, emergency_contact,
       emergency_phone, status, notes, created_at, updated_at
FROM students
WHERE organization_id = ?
ORDER BY status, name, id
`

func (q *Queries) ListStudents(ctx context.Context, organizationID uint64) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, listStudents, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SchoolID,
			&i.TermID,
			&i.SchoolClassID,
			&i.CareClassID,
			&i.Name,
			&i.Gender,
			&i.BirthDate,
			&i.StudentNo,
			&i.GuardianPhone,
			&i.EmergencyContact,
			&i.EmergencyPhone,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsetCurrentAcademicTerms = `-- name: UnsetCurrentAcademicTerms :exec
UPDATE academic_terms
SET is_current = FALSE
WHERE organization_id = ? AND is_current = TRUE
`

func (q *Queries) UnsetCurrentAcademicTerms(ctx context.Context, organizationID uint64) error {
	_, err := q.db.ExecContext(ctx, unsetCurrentAcademicTerms, organizationID)
	return err
}

const updateStudent = `-- name: UpdateStudent :execresult
UPDATE students
SET school_id = ?, term_id = ?, school_class_id = ?, care_class_id = ?,
    name = ?, gender = ?, birth_date = ?, student_no = ?, guardian_phone = ?,
    emergency_contact = ?, emergency_phone = ?, status = ?, notes = ?
WHERE id = ? AND organization_id = ?
`

type UpdateStudentParams struct {
	SchoolID         uint64        `json:"school_id"`
	TermID           uint64        `json:"term_id"`
	SchoolClassID    uint64        `json:"school_class_id"`
	CareClassID      sql.NullInt64 `json:"care_class_id"`
	Name             string        `json:"name"`
	Gender           string        `json:"gender"`
	BirthDate        sql.NullTime  `json:"birth_date"`
	StudentNo        string        `json:"student_no"`
	GuardianPhone    string        `json:"guardian_phone"`
	EmergencyContact string        `json:"emergency_contact"`
	EmergencyPhone   string        `json:"emergency_phone"`
	Status           string        `json:"status"`
	Notes            string        `json:"notes"`
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateStudent,
		arg.SchoolID,
		arg.TermID,
		arg.SchoolClassID,
		arg.CareClassID,
		arg.Name,
		arg.Gender,
		arg.BirthDate,
		arg.StudentNo,
		arg.GuardianPhone,
		arg.EmergencyContact,
		arg.EmergencyPhone,
		arg.Status,
		arg.Notes,
		arg.ID,
		arg.OrganizationID,
	)
}
