// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meals.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createDietNoteChangeRequest = `-- name: CreateDietNoteChangeRequest :execresult
INSERT INTO diet_note_change_requests (
    organization_id, student_id, parent_account_id, current_note, requested_note, status
) VALUES (?, ?, ?, ?, ?, 'pending')
`

type CreateDietNoteChangeRequestParams struct {
	OrganizationID  uint64 `json:"organization_id"`
	StudentID       uint64 `json:"student_id"`
	ParentAccountID uint64 `json:"parent_account_id"`
	CurrentNote     string `json:"current_note"`
	RequestedNote   string `json:"requested_note"`
}

func (q *Queries) CreateDietNoteChangeRequest(ctx context.Context, arg CreateDietNoteChangeRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDietNoteChangeRequest,
		arg.OrganizationID,
		arg.StudentID,
		arg.ParentAccountID,
		arg.CurrentNote,
		arg.RequestedNote,
	)
}

const createMealPlan = `-- name: CreateMealPlan :execresult
INSERT INTO meal_plans (organization_id, meal_date, menu_text, photo_url, adjustment_note, created_by_user_id, created_by_name, status)
VALUES (?, ?, ?, ?, ?, ?, ?, 'active')
`

type CreateMealPlanParams struct {
	OrganizationID  uint64        `json:"organization_id"`
	MealDate        time.Time     `json:"meal_date"`
	MenuText        string        `json:"menu_text"`
	PhotoUrl        string        `json:"photo_url"`
	AdjustmentNote  string        `json:"adjustment_note"`
	CreatedByUserID sql.NullInt64 `json:"created_by_user_id"`
	CreatedByName   string        `json:"created_by_name"`
}

func (q *Queries) CreateMealPlan(ctx context.Context, arg CreateMealPlanParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMealPlan,
		arg.OrganizationID,
		arg.MealDate,
		arg.MenuText,
		arg.PhotoUrl,
		arg.AdjustmentNote,
		arg.CreatedByUserID,
		arg.CreatedByName,
	)
}

const createStudentDietNote = `-- name: CreateStudentDietNote :execresult
INSERT INTO student_diet_notes (organization_id, student_id, note, updated_by_user_id, updated_by_name)
VALUES (?, ?, ?, ?, ?)
`

type CreateStudentDietNoteParams struct {
	OrganizationID  uint64        `json:"organization_id"`
	StudentID       uint64        `json:"student_id"`
	Note            string        `json:"note"`
	UpdatedByUserID sql.NullInt64 `json:"updated_by_user_id"`
	UpdatedByName   string        `json:"updated_by_name"`
}

func (q *Queries) CreateStudentDietNote(ctx context.Context, arg CreateStudentDietNoteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createStudentDietNote,
		arg.OrganizationID,
		arg.StudentID,
		arg.Note,
		arg.UpdatedByUserID,
		arg.UpdatedByName,
	)
}

const getDietNoteChangeRequest = `-- name: GetDietNoteChangeRequest :one
SELECT id, organization_id, student_id, parent_account_id, current_note, requested_note,
       status, review_note, reviewed_by_user_id, reviewed_at, created_at, updated_at
FROM diet_note_change_requests
WHERE organization_id = ? AND id = ?
LIMIT 1
`

type GetDietNoteChangeRequestParams struct {
	OrganizationID uint64 `json:"organization_id"`
	ID             uint64 `json:"id"`
}

func (q *Queries) GetDietNoteChangeRequest(ctx context.Context, arg GetDietNoteChangeRequestParams) (DietNoteChangeRequest, error) {
	row := q.db.QueryRowContext(ctx, getDietNoteChangeRequest, arg.OrganizationID, arg.ID)
	var i DietNoteChangeRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StudentID,
		&i.ParentAccountID,
		&i.CurrentNote,
		&i.RequestedNote,
		&i.Status,
		&i.ReviewNote,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMealPlanByDate = `-- name: GetMealPlanByDate :one
SELECT id, organization_id, meal_date, menu_text, photo_url, adjustment_note,
       created_by_user_id, created_by_name, status, created_at, updated_at
FROM meal_plans WHERE organization_id = ? AND meal_date = ? LIMIT 1
`

type GetMealPlanByDateParams struct {
	OrganizationID uint64    `json:"organization_id"`
	MealDate       time.Time `json:"meal_date"`
}

func (q *Queries) GetMealPlanByDate(ctx context.Context, arg GetMealPlanByDateParams) (MealPlan, error) {
	row := q.db.QueryRowContext(ctx, getMealPlanByDate, arg.OrganizationID, arg.MealDate)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MealDate,
		&i.MenuText,
		&i.PhotoUrl,
		&i.AdjustmentNote,
		&i.CreatedByUserID,
		&i.CreatedByName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMealPlanByID = `-- name: GetMealPlanByID :one
SELECT id, organization_id, meal_date, menu_text, photo_url, adjustment_note,
       created_by_user_id, created_by_name, status, created_at, updated_at
FROM meal_plans WHERE organization_id = ? AND id = ? LIMIT 1
`

type GetMealPlanByIDParams struct {
	OrganizationID uint64 `json:"organization_id"`
	ID             uint64 `json:"id"`
}

func (q *Queries) GetMealPlanByID(ctx context.Context, arg GetMealPlanByIDParams) (MealPlan, error) {
	row := q.db.QueryRowContext(ctx, getMealPlanByID, arg.OrganizationID, arg.ID)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MealDate,
		&i.MenuText,
		&i.PhotoUrl,
		&i.AdjustmentNote,
		&i.CreatedByUserID,
		&i.CreatedByName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingDietNoteChangeRequest = `-- name: GetPendingDietNoteChangeRequest :one
SELECT id, organization_id, student_id, parent_account_id, current_note, requested_note,
       status, review_note, reviewed_by_user_id, reviewed_at, created_at, updated_at
FROM diet_note_change_requests
WHERE organization_id = ? AND student_id = ? AND status = 'pending'
ORDER BY id DESC
LIMIT 1
FOR UPDATE
`

type GetPendingDietNoteChangeRequestParams struct {
	OrganizationID uint64 `json:"organization_id"`
	StudentID      uint64 `json:"student_id"`
}

func (q *Queries) GetPendingDietNoteChangeRequest(ctx context.Context, arg GetPendingDietNoteChangeRequestParams) (DietNoteChangeRequest, error) {
	row := q.db.QueryRowContext(ctx, getPendingDietNoteChangeRequest, arg.OrganizationID, arg.StudentID)
	var i DietNoteChangeRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StudentID,
		&i.ParentAccountID,
		&i.CurrentNote,
		&i.RequestedNote,
		&i.Status,
		&i.ReviewNote,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentDietNote = `-- name: GetStudentDietNote :one
SELECT id, organization_id, student_id, note, updated_by_user_id, updated_by_name, created_at, updated_at
FROM student_diet_notes WHERE organization_id = ? AND student_id = ? LIMIT 1
`

type GetStudentDietNoteParams struct {
	OrganizationID uint64 `json:"organization_id"`
	StudentID      uint64 `json:"student_id"`
}

func (q *Queries) GetStudentDietNote(ctx context.Context, arg GetStudentDietNoteParams) (StudentDietNote, error) {
	row := q.db.QueryRowContext(ctx, getStudentDietNote, arg.OrganizationID, arg.StudentID)
	var i StudentDietNote
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StudentID,
		&i.Note,
		&i.UpdatedByUserID,
		&i.UpdatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDietNoteChangeRequests = `-- name: ListDietNoteChangeRequests :many
SELECT id, organization_id, student_id, parent_account_id, current_note, requested_note,
       status, review_note, reviewed_by_user_id, reviewed_at, created_at, updated_at
FROM diet_note_change_requests
WHERE organization_id = ?
  AND (? IS NULL OR student_id = ?)
  AND (? IS NULL OR status = ?)
ORDER BY CASE WHEN status = 'pending' THEN 0 ELSE 1 END, created_at DESC, id DESC
`

type ListDietNoteChangeRequestsParams struct {
	OrganizationID  uint64         `json:"organization_id"`
	StudentIDFilter sql.NullInt64  `json:"student_id_filter"`
	StatusFilter    sql.NullString `json:"status_filter"`
}

func (q *Queries) ListDietNoteChangeRequests(ctx context.Context, arg ListDietNoteChangeRequestsParams) ([]DietNoteChangeRequest, error) {
	rows, err := q.db.QueryContext(ctx, listDietNoteChangeRequests,
		arg.OrganizationID,
		arg.StudentIDFilter,
		arg.StudentIDFilter,
		arg.StatusFilter,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DietNoteChangeRequest{}
	for rows.Next() {
		var i DietNoteChangeRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StudentID,
			&i.ParentAccountID,
			&i.CurrentNote,
			&i.RequestedNote,
			&i.Status,
			&i.ReviewNote,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealPlans = `-- name: ListMealPlans :many
SELECT id, organization_id, meal_date, menu_text, photo_url, adjustment_note,
       created_by_user_id, created_by_name, status, created_at, updated_at
FROM meal_plans
WHERE organization_id = ?
  AND (? IS NULL OR meal_date >= ?)
  AND (? IS NULL OR meal_date <= ?)
ORDER BY meal_date DESC, id DESC
`

type ListMealPlansParams struct {
	OrganizationID uint64       `json:"organization_id"`
	FromDate       sql.NullTime `json:"from_date"`
	ToDate         sql.NullTime `json:"to_date"`
}

func (q *Queries) ListMealPlans(ctx context.Context, arg ListMealPlansParams) ([]MealPlan, error) {
	rows, err := q.db.QueryContext(ctx, listMealPlans,
		arg.OrganizationID,
		arg.FromDate,
		arg.FromDate,
		arg.ToDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealPlan{}
	for rows.Next() {
		var i MealPlan
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MealDate,
			&i.MenuText,
			&i.PhotoUrl,
			&i.AdjustmentNote,
			&i.CreatedByUserID,
			&i.CreatedByName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentDietNotes = `-- name: ListStudentDietNotes :many
SELECT id, organization_id, student_id, note, updated_by_user_id, updated_by_name, created_at, updated_at
FROM student_diet_notes
WHERE organization_id = ? AND (? IS NULL OR student_id = ?)
ORDER BY student_id
`

type ListStudentDietNotesParams struct {
	OrganizationID  uint64        `json:"organization_id"`
	StudentIDFilter sql.NullInt64 `json:"student_id_filter"`
}

func (q *Queries) ListStudentDietNotes(ctx context.Context, arg ListStudentDietNotesParams) ([]StudentDietNote, error) {
	rows, err := q.db.QueryContext(ctx, listStudentDietNotes, arg.OrganizationID, arg.StudentIDFilter, arg.StudentIDFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentDietNote{}
	for rows.Next() {
		var i StudentDietNote
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StudentID,
			&i.Note,
			&i.UpdatedByUserID,
			&i.UpdatedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewDietNoteChangeRequest = `-- name: ReviewDietNoteChangeRequest :execresult
UPDATE diet_note_change_requests
SET status = ?, review_note = ?, reviewed_by_user_id = ?, reviewed_at = ?, updated_at = CURRENT_TIMESTAMP(3)
WHERE organization_id = ? AND id = ? AND status = 'pending'
`

type ReviewDietNoteChangeRequestParams struct {
	Status           string        `json:"status"`
	ReviewNote       string        `json:"review_note"`
	ReviewedByUserID sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt       sql.NullTime  `json:"reviewed_at"`
	OrganizationID   uint64        `json:"organization_id"`
	ID               uint64        `json:"id"`
}

func (q *Queries) ReviewDietNoteChangeRequest(ctx context.Context, arg ReviewDietNoteChangeRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, reviewDietNoteChangeRequest,
		arg.Status,
		arg.ReviewNote,
		arg.ReviewedByUserID,
		arg.ReviewedAt,
		arg.OrganizationID,
		arg.ID,
	)
}

const updateMealPlan = `-- name: UpdateMealPlan :execresult
UPDATE meal_plans
SET menu_text = ?, photo_url = ?, adjustment_note = ?, created_by_user_id = ?, created_by_name = ?, status = 'active', updated_at = CURRENT_TIMESTAMP(3)
WHERE organization_id = ? AND id = ?
`

type UpdateMealPlanParams struct {
	MenuText        string        `json:"menu_text"`
	PhotoUrl        string        `json:"photo_url"`
	AdjustmentNote  string        `json:"adjustment_note"`
	CreatedByUserID sql.NullInt64 `json:"created_by_user_id"`
	CreatedByName   string        `json:"created_by_name"`
	OrganizationID  uint64        `json:"organization_id"`
	ID              uint64        `json:"id"`
}

func (q *Queries) UpdateMealPlan(ctx context.Context, arg UpdateMealPlanParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateMealPlan,
		arg.MenuText,
		arg.PhotoUrl,
		arg.AdjustmentNote,
		arg.CreatedByUserID,
		arg.CreatedByName,
		arg.OrganizationID,
		arg.ID,
	)
}

const updateStudentDietNote = `-- name: UpdateStudentDietNote :execresult
UPDATE student_diet_notes
SET note = ?, updated_by_user_id = ?, updated_by_name = ?, updated_at = CURRENT_TIMESTAMP(3)
WHERE organization_id = ? AND student_id = ?
`

type UpdateStudentDietNoteParams struct {
	Note            string        `json:"note"`
	UpdatedByUserID sql.NullInt64 `json:"updated_by_user_id"`
	UpdatedByName   string        `json:"updated_by_name"`
	OrganizationID  uint64        `json:"organization_id"`
	StudentID       uint64        `json:"student_id"`
}

func (q *Queries) UpdateStudentDietNote(ctx context.Context, arg UpdateStudentDietNoteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateStudentDietNote,
		arg.Note,
		arg.UpdatedByUserID,
		arg.UpdatedByName,
		arg.OrganizationID,
		arg.StudentID,
	)
}
