// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AcademicTerm struct {
	ID             uint64    `json:"id"`
	OrganizationID uint64    `json:"organization_id"`
	Name           string    `json:"name"`
	StartsOn       time.Time `json:"starts_on"`
	EndsOn         time.Time `json:"ends_on"`
	IsCurrent      bool      `json:"is_current"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type AuditLog struct {
	ID             uint64          `json:"id"`
	OrganizationID uint64          `json:"organization_id"`
	ActorType      string          `json:"actor_type"`
	ActorID        sql.NullInt64   `json:"actor_id"`
	Action         string          `json:"action"`
	ResourceType   string          `json:"resource_type"`
	ResourceID     sql.NullInt64   `json:"resource_id"`
	MetadataJson   json.RawMessage `json:"metadata_json"`
	RequestID      string          `json:"request_id"`
	CreatedAt      time.Time       `json:"created_at"`
}

type CareClass struct {
	ID             uint64    `json:"id"`
	OrganizationID uint64    `json:"organization_id"`
	Name           string    `json:"name"`
	Capacity       uint32    `json:"capacity"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type DailySummary struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	SummaryDate      time.Time     `json:"summary_date"`
	Content          string        `json:"content"`
	ChildUpdatesJson string        `json:"child_updates_json"`
	Status           string        `json:"status"`
	CreatedByUserID  sql.NullInt64 `json:"created_by_user_id"`
	CreatedByName    string        `json:"created_by_name"`
	GeneratedAt      sql.NullTime  `json:"generated_at"`
	PublishedAt      sql.NullTime  `json:"published_at"`
	ClosedAt         sql.NullTime  `json:"closed_at"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	CurrentVersion   uint32        `json:"current_version"`
	WithdrawnAt      sql.NullTime  `json:"withdrawn_at"`
	WithdrawalReason string        `json:"withdrawal_reason"`
	CorrectionReason string        `json:"correction_reason"`
}

type DailySummaryRead struct {
	ID              uint64    `json:"id"`
	OrganizationID  uint64    `json:"organization_id"`
	DailySummaryID  uint64    `json:"daily_summary_id"`
	ParentAccountID uint64    `json:"parent_account_id"`
	ReadVersion     uint32    `json:"read_version"`
	ReadAt          time.Time `json:"read_at"`
}

type DailySummaryVersion struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	DailySummaryID   uint64        `json:"daily_summary_id"`
	Version          uint32        `json:"version"`
	Action           string        `json:"action"`
	Content          string        `json:"content"`
	ChildUpdatesJson string        `json:"child_updates_json"`
	Reason           string        `json:"reason"`
	CreatedByUserID  sql.NullInt64 `json:"created_by_user_id"`
	CreatedByName    string        `json:"created_by_name"`
	CreatedAt        time.Time     `json:"created_at"`
}

type DietNoteChangeRequest struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	StudentID        uint64        `json:"student_id"`
	ParentAccountID  uint64        `json:"parent_account_id"`
	CurrentNote      string        `json:"current_note"`
	RequestedNote    string        `json:"requested_note"`
	Status           string        `json:"status"`
	ReviewNote       string        `json:"review_note"`
	ReviewedByUserID sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt       sql.NullTime  `json:"reviewed_at"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

type HomeworkTask struct {
	ID              uint64          `json:"id"`
	OrganizationID  uint64          `json:"organization_id"`
	HomeworkDate    time.Time       `json:"homework_date"`
	SchoolID        uint64          `json:"school_id"`
	SchoolClassID   uint64          `json:"school_class_id"`
	Subject         string          `json:"subject"`
	Content         string          `json:"content"`
	CreatedByUserID sql.NullInt64   `json:"created_by_user_id"`
	CreatorName     string          `json:"creator_name"`
	Status          string          `json:"status"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	AttachmentUrls  json.RawMessage `json:"attachment_urls"`
}

type HomeworkTaskStudent struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	TaskID           uint64        `json:"task_id"`
	StudentID        uint64        `json:"student_id"`
	Status           string        `json:"status"`
	CorrectionNote   string        `json:"correction_note"`
	ReviewedByUserID sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt       sql.NullTime  `json:"reviewed_at"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

type LeaveRequest struct {
	ID                uint64        `json:"id"`
	OrganizationID    uint64        `json:"organization_id"`
	StudentID         uint64        `json:"student_id"`
	ParentAccountID   sql.NullInt64 `json:"parent_account_id"`
	SubmittedByType   string        `json:"submitted_by_type"`
	SubmittedByUserID sql.NullInt64 `json:"submitted_by_user_id"`
	LeaveDate         time.Time     `json:"leave_date"`
	Reason            string        `json:"reason"`
	Status            string        `json:"status"`
	TeacherNote       string        `json:"teacher_note"`
	ReviewedByUserID  sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt        sql.NullTime  `json:"reviewed_at"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
}

type MealPlan struct {
	ID              uint64        `json:"id"`
	OrganizationID  uint64        `json:"organization_id"`
	MealDate        time.Time     `json:"meal_date"`
	MenuText        string        `json:"menu_text"`
	PhotoUrl        string        `json:"photo_url"`
	AdjustmentNote  string        `json:"adjustment_note"`
	CreatedByUserID sql.NullInt64 `json:"created_by_user_id"`
	CreatedByName   string        `json:"created_by_name"`
	Status          string        `json:"status"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

type MediaAsset struct {
	ID              uint64        `json:"id"`
	OrganizationID  uint64        `json:"organization_id"`
	ObjectKey       string        `json:"object_key"`
	ResourceType    string        `json:"resource_type"`
	ResourceID      sql.NullInt64 `json:"resource_id"`
	OwnerType       string        `json:"owner_type"`
	OwnerID         sql.NullInt64 `json:"owner_id"`
	ContentType     string        `json:"content_type"`
	SizeBytes       uint64        `json:"size_bytes"`
	Sha256Hex       string        `json:"sha256_hex"`
	Status          string        `json:"status"`
	RetentionUntil  sql.NullTime  `json:"retention_until"`
	CreatedByUserID sql.NullInt64 `json:"created_by_user_id"`
	CreatedAt       time.Time     `json:"created_at"`
	DeletedAt       sql.NullTime  `json:"deleted_at"`
}

type Notification struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	StudentID        uint64        `json:"student_id"`
	OperationID      sql.NullInt64 `json:"operation_id"`
	EventID          sql.NullInt64 `json:"event_id"`
	RecipientType    string        `json:"recipient_type"`
	Kind             string        `json:"kind"`
	Title            string        `json:"title"`
	Content          string        `json:"content"`
	Status           string        `json:"status"`
	SentAt           sql.NullTime  `json:"sent_at"`
	CreatedAt        time.Time     `json:"created_at"`
	ReadAt           sql.NullTime  `json:"read_at"`
	DeliveryAttempts uint32        `json:"delivery_attempts"`
	LastAttemptAt    sql.NullTime  `json:"last_attempt_at"`
	DeliveryError    string        `json:"delivery_error"`
	NextRetryAt      sql.NullTime  `json:"next_retry_at"`
}

type NotificationDeliveryLog struct {
	ID              uint64       `json:"id"`
	OrganizationID  uint64       `json:"organization_id"`
	NotificationID  uint64       `json:"notification_id"`
	ParentAccountID uint64       `json:"parent_account_id"`
	MessageKind     string       `json:"message_kind"`
	TemplateID      string       `json:"template_id"`
	Status          string       `json:"status"`
	Attempts        uint32       `json:"attempts"`
	LastAttemptAt   sql.NullTime `json:"last_attempt_at"`
	SentAt          sql.NullTime `json:"sent_at"`
	NextRetryAt     sql.NullTime `json:"next_retry_at"`
	DeliveryError   string       `json:"delivery_error"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

type Organization struct {
	ID        uint64    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type OutboxEvent struct {
	ID             uint64          `json:"id"`
	OrganizationID uint64          `json:"organization_id"`
	EventType      string          `json:"event_type"`
	AggregateType  string          `json:"aggregate_type"`
	AggregateID    uint64          `json:"aggregate_id"`
	NotificationID uint64          `json:"notification_id"`
	PayloadJson    json.RawMessage `json:"payload_json"`
	Status         string          `json:"status"`
	Attempts       uint32          `json:"attempts"`
	AvailableAt    time.Time       `json:"available_at"`
	LockedAt       sql.NullTime    `json:"locked_at"`
	ProcessedAt    sql.NullTime    `json:"processed_at"`
	LastError      string          `json:"last_error"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type ParentAccount struct {
	ID             uint64    `json:"id"`
	OrganizationID uint64    `json:"organization_id"`
	Openid         string    `json:"openid"`
	Nickname       string    `json:"nickname"`
	Avatar         string    `json:"avatar"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ParentChildApplication struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	ParentAccountID  uint64        `json:"parent_account_id"`
	StudentID        sql.NullInt64 `json:"student_id"`
	SchoolID         sql.NullInt64 `json:"school_id"`
	SchoolClassID    sql.NullInt64 `json:"school_class_id"`
	StudentName      string        `json:"student_name"`
	SchoolNameInput  string        `json:"school_name_input"`
	GradeInput       string        `json:"grade_input"`
	ClassNameInput   string        `json:"class_name_input"`
	Grade            string        `json:"grade"`
	ClassName        string        `json:"class_name"`
	GuardianName     string        `json:"guardian_name"`
	GuardianPhone    string        `json:"guardian_phone"`
	Relationship     string        `json:"relationship"`
	Notes            string        `json:"notes"`
	Status           string        `json:"status"`
	ReviewNote       string        `json:"review_note"`
	ReviewedByUserID sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt       sql.NullTime  `json:"reviewed_at"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

type ParentMessageSubscription struct {
	ID              uint64       `json:"id"`
	OrganizationID  uint64       `json:"organization_id"`
	ParentAccountID uint64       `json:"parent_account_id"`
	MessageKind     string       `json:"message_kind"`
	Status          string       `json:"status"`
	UpdatedAt       time.Time    `json:"updated_at"`
	AuthorizedAt    sql.NullTime `json:"authorized_at"`
	TemplateVersion string       `json:"template_version"`
}

type ParentPrivacyConsent struct {
	ID              uint64    `json:"id"`
	OrganizationID  uint64    `json:"organization_id"`
	ParentAccountID uint64    `json:"parent_account_id"`
	PolicyVersion   string    `json:"policy_version"`
	ConsentedAt     time.Time `json:"consented_at"`
	CreatedAt       time.Time `json:"created_at"`
}

type ParentStudentBinding struct {
	ID              uint64    `json:"id"`
	OrganizationID  uint64    `json:"organization_id"`
	ParentAccountID uint64    `json:"parent_account_id"`
	StudentID       uint64    `json:"student_id"`
	Relationship    string    `json:"relationship"`
	IsPrimary       bool      `json:"is_primary"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type PickupChangeRequest struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	StudentID        uint64        `json:"student_id"`
	OperationID      sql.NullInt64 `json:"operation_id"`
	ChangeDate       time.Time     `json:"change_date"`
	RequestedStatus  string        `json:"requested_status"`
	Note             string        `json:"note"`
	SubmittedBy      string        `json:"submitted_by"`
	Status           string        `json:"status"`
	ReviewedByUserID sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt       sql.NullTime  `json:"reviewed_at"`
	ReviewNote       string        `json:"review_note"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

type PickupEvent struct {
	ID                 uint64    `json:"id"`
	OrganizationID     uint64    `json:"organization_id"`
	OperationID        uint64    `json:"operation_id"`
	OperationStudentID uint64    `json:"operation_student_id"`
	StudentID          uint64    `json:"student_id"`
	EventType          string    `json:"event_type"`
	EventAt            time.Time `json:"event_at"`
	OperatorName       string    `json:"operator_name"`
	PhotoUrl           string    `json:"photo_url"`
	Note               string    `json:"note"`
}

type PickupOperation struct {
	ID                     uint64        `json:"id"`
	OrganizationID         uint64        `json:"organization_id"`
	OperationDate          time.Time     `json:"operation_date"`
	PickupMode             string        `json:"pickup_mode"`
	SchoolID               uint64        `json:"school_id"`
	SchoolClassID          uint64        `json:"school_class_id"`
	CareClassID            sql.NullInt64 `json:"care_class_id"`
	TeacherUserID          sql.NullInt64 `json:"teacher_user_id"`
	TeacherName            string        `json:"teacher_name"`
	Status                 string        `json:"status"`
	StartedAt              sql.NullTime  `json:"started_at"`
	FinishedAt             sql.NullTime  `json:"finished_at"`
	Notes                  string        `json:"notes"`
	CreatedAt              time.Time     `json:"created_at"`
	UpdatedAt              time.Time     `json:"updated_at"`
	ConfirmedAt            sql.NullTime  `json:"confirmed_at"`
	ConfirmedByUserID      sql.NullInt64 `json:"confirmed_by_user_id"`
	ConfirmedByName        string        `json:"confirmed_by_name"`
	ExecutingTeacherUserID sql.NullInt64 `json:"executing_teacher_user_id"`
	ExecutingTeacherName   string        `json:"executing_teacher_name"`
	TeacherRole            string        `json:"teacher_role"`
	ExpectedPickupTime     string        `json:"expected_pickup_time"`
}

type PickupOperationHandoff struct {
	ID                uint64        `json:"id"`
	OrganizationID    uint64        `json:"organization_id"`
	OperationID       uint64        `json:"operation_id"`
	FromTeacherUserID sql.NullInt64 `json:"from_teacher_user_id"`
	FromTeacherName   string        `json:"from_teacher_name"`
	ToTeacherUserID   uint64        `json:"to_teacher_user_id"`
	ToTeacherName     string        `json:"to_teacher_name"`
	TeacherRole       string        `json:"teacher_role"`
	Note              string        `json:"note"`
	HandoffAt         time.Time     `json:"handoff_at"`
	CreatedByUserID   sql.NullInt64 `json:"created_by_user_id"`
	CreatedByName     string        `json:"created_by_name"`
}

type PickupOperationStudent struct {
	ID             uint64       `json:"id"`
	OrganizationID uint64       `json:"organization_id"`
	OperationID    uint64       `json:"operation_id"`
	StudentID      uint64       `json:"student_id"`
	Status         string       `json:"status"`
	PhotoUrl       string       `json:"photo_url"`
	CheckedAt      sql.NullTime `json:"checked_at"`
	Note           string       `json:"note"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	IsTemporary    bool         `json:"is_temporary"`
	ProfilePending bool         `json:"profile_pending"`
	PickupMode     string       `json:"pickup_mode"`
}

type School struct {
	ID             uint64    `json:"id"`
	OrganizationID uint64    `json:"organization_id"`
	Name           string    `json:"name"`
	Address        string    `json:"address"`
	ContactPhone   string    `json:"contact_phone"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type SchoolClass struct {
	ID             uint64    `json:"id"`
	OrganizationID uint64    `json:"organization_id"`
	SchoolID       uint64    `json:"school_id"`
	TermID         uint64    `json:"term_id"`
	Grade          string    `json:"grade"`
	Name           string    `json:"name"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Student struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	SchoolID         uint64        `json:"school_id"`
	TermID           uint64        `json:"term_id"`
	SchoolClassID    uint64        `json:"school_class_id"`
	CareClassID      sql.NullInt64 `json:"care_class_id"`
	Name             string        `json:"name"`
	Gender           string        `json:"gender"`
	BirthDate        sql.NullTime  `json:"birth_date"`
	StudentNo        string        `json:"student_no"`
	GuardianPhone    string        `json:"guardian_phone"`
	EmergencyContact string        `json:"emergency_contact"`
	EmergencyPhone   string        `json:"emergency_phone"`
	Status           string        `json:"status"`
	Notes            string        `json:"notes"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

type StudentDietNote struct {
	ID              uint64        `json:"id"`
	OrganizationID  uint64        `json:"organization_id"`
	StudentID       uint64        `json:"student_id"`
	Note            string        `json:"note"`
	UpdatedByUserID sql.NullInt64 `json:"updated_by_user_id"`
	UpdatedByName   string        `json:"updated_by_name"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

type TeacherClassAssignment struct {
	ID             uint64    `json:"id"`
	OrganizationID uint64    `json:"organization_id"`
	TeacherUserID  uint64    `json:"teacher_user_id"`
	SchoolClassID  uint64    `json:"school_class_id"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type User struct {
	ID           uint64    `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Nickname     string    `json:"nickname"`
	Avatar       string    `json:"avatar"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Role         string    `json:"role"`
}
