// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_outbox.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const claimNotificationOutbox = `-- name: ClaimNotificationOutbox :execresult
UPDATE outbox_events
SET status = 'processing', attempts = attempts + 1, locked_at = ?, updated_at = CURRENT_TIMESTAMP(3)
WHERE id = ? AND organization_id = ?
  AND status IN ('pending', 'failed')
  AND (locked_at IS NULL OR locked_at <= ?)
`

type ClaimNotificationOutboxParams struct {
	LockedAt       sql.NullTime `json:"locked_at"`
	ID             uint64       `json:"id"`
	OrganizationID uint64       `json:"organization_id"`
	LockedAt_2     sql.NullTime `json:"locked_at_2"`
}

func (q *Queries) ClaimNotificationOutbox(ctx context.Context, arg ClaimNotificationOutboxParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, claimNotificationOutbox,
		arg.LockedAt,
		arg.ID,
		arg.OrganizationID,
		arg.LockedAt_2,
	)
}

const completeNotificationOutbox = `-- name: CompleteNotificationOutbox :execresult
UPDATE outbox_events
SET status = ?, available_at = COALESCE(?, available_at), locked_at = NULL,
    processed_at = CASE WHEN ? = 'processed' THEN CURRENT_TIMESTAMP(3) ELSE processed_at END,
    last_error = ?, updated_at = CURRENT_TIMESTAMP(3)
WHERE id = ? AND organization_id = ? AND status = 'processing'
`

type CompleteNotificationOutboxParams struct {
	Status         string      `json:"status"`
	AvailableAt    time.Time   `json:"available_at"`
	Column3        interface{} `json:"column_3"`
	LastError      string      `json:"last_error"`
	ID             uint64      `json:"id"`
	OrganizationID uint64      `json:"organization_id"`
}

func (q *Queries) CompleteNotificationOutbox(ctx context.Context, arg CompleteNotificationOutboxParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, completeNotificationOutbox,
		arg.Status,
		arg.AvailableAt,
		arg.Column3,
		arg.LastError,
		arg.ID,
		arg.OrganizationID,
	)
}

const createNotificationDeliveryLog = `-- name: CreateNotificationDeliveryLog :execresult
INSERT INTO notification_delivery_logs (
    organization_id, notification_id, parent_account_id, message_kind, template_id, status
) VALUES (?, ?, ?, ?, ?, 'pending')
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id)
`

type CreateNotificationDeliveryLogParams struct {
	OrganizationID  uint64 `json:"organization_id"`
	NotificationID  uint64 `json:"notification_id"`
	ParentAccountID uint64 `json:"parent_account_id"`
	MessageKind     string `json:"message_kind"`
	TemplateID      string `json:"template_id"`
}

func (q *Queries) CreateNotificationDeliveryLog(ctx context.Context, arg CreateNotificationDeliveryLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNotificationDeliveryLog,
		arg.OrganizationID,
		arg.NotificationID,
		arg.ParentAccountID,
		arg.MessageKind,
		arg.TemplateID,
	)
}

const createNotificationOutbox = `-- name: CreateNotificationOutbox :execresult
INSERT INTO outbox_events (
    organization_id, event_type, aggregate_type, aggregate_id,
    notification_id, payload_json, status, available_at
) VALUES (?, 'notification.created', 'notification', ?, ?, JSON_OBJECT('notification_id', ?), 'pending', CURRENT_TIMESTAMP(3))
`

type CreateNotificationOutboxParams struct {
	OrganizationID uint64      `json:"organization_id"`
	AggregateID    uint64      `json:"aggregate_id"`
	NotificationID uint64      `json:"notification_id"`
	JSONOBJECT     interface{} `json:"JSON_OBJECT"`
}

func (q *Queries) CreateNotificationOutbox(ctx context.Context, arg CreateNotificationOutboxParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNotificationOutbox,
		arg.OrganizationID,
		arg.AggregateID,
		arg.NotificationID,
		arg.JSONOBJECT,
	)
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, organization_id, student_id, operation_id, event_id, recipient_type,
       kind, title, content, status, sent_at, delivery_attempts, last_attempt_at,
       delivery_error, next_retry_at, read_at, created_at
FROM notifications
WHERE id = ? AND organization_id = ?
LIMIT 1
`

type GetNotificationByIDParams struct {
	ID             uint64 `json:"id"`
	OrganizationID uint64 `json:"organization_id"`
}

type GetNotificationByIDRow struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	StudentID        uint64        `json:"student_id"`
	OperationID      sql.NullInt64 `json:"operation_id"`
	EventID          sql.NullInt64 `json:"event_id"`
	RecipientType    string        `json:"recipient_type"`
	Kind             string        `json:"kind"`
	Title            string        `json:"title"`
	Content          string        `json:"content"`
	Status           string        `json:"status"`
	SentAt           sql.NullTime  `json:"sent_at"`
	DeliveryAttempts uint32        `json:"delivery_attempts"`
	LastAttemptAt    sql.NullTime  `json:"last_attempt_at"`
	DeliveryError    string        `json:"delivery_error"`
	NextRetryAt      sql.NullTime  `json:"next_retry_at"`
	ReadAt           sql.NullTime  `json:"read_at"`
	CreatedAt        time.Time     `json:"created_at"`
}

func (q *Queries) GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (GetNotificationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, arg.ID, arg.OrganizationID)
	var i GetNotificationByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StudentID,
		&i.OperationID,
		&i.EventID,
		&i.RecipientType,
		&i.Kind,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.SentAt,
		&i.DeliveryAttempts,
		&i.LastAttemptAt,
		&i.DeliveryError,
		&i.NextRetryAt,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationDeliveryLogByID = `-- name: GetNotificationDeliveryLogByID :one
SELECT id, organization_id, notification_id, parent_account_id, message_kind,
       template_id, status, attempts, last_attempt_at, sent_at, next_retry_at,
       delivery_error, created_at, updated_at
FROM notification_delivery_logs
WHERE id = ? AND organization_id = ?
LIMIT 1
`

type GetNotificationDeliveryLogByIDParams struct {
	ID             uint64 `json:"id"`
	OrganizationID uint64 `json:"organization_id"`
}

func (q *Queries) GetNotificationDeliveryLogByID(ctx context.Context, arg GetNotificationDeliveryLogByIDParams) (NotificationDeliveryLog, error) {
	row := q.db.QueryRowContext(ctx, getNotificationDeliveryLogByID, arg.ID, arg.OrganizationID)
	var i NotificationDeliveryLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.NotificationID,
		&i.ParentAccountID,
		&i.MessageKind,
		&i.TemplateID,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.SentAt,
		&i.NextRetryAt,
		&i.DeliveryError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationDeliveryLogs = `-- name: ListNotificationDeliveryLogs :many
SELECT id, organization_id, notification_id, parent_account_id, message_kind,
       template_id, status, attempts, last_attempt_at, sent_at, next_retry_at,
       delivery_error, created_at, updated_at
FROM notification_delivery_logs
WHERE organization_id = ?
  AND (? IS NULL OR notification_id = ?)
  AND (? IS NULL OR status = ?)
ORDER BY id DESC
`

type ListNotificationDeliveryLogsParams struct {
	OrganizationID       uint64         `json:"organization_id"`
	NotificationIDFilter sql.NullInt64  `json:"notification_id_filter"`
	StatusFilter         sql.NullString `json:"status_filter"`
}

func (q *Queries) ListNotificationDeliveryLogs(ctx context.Context, arg ListNotificationDeliveryLogsParams) ([]NotificationDeliveryLog, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationDeliveryLogs,
		arg.OrganizationID,
		arg.NotificationIDFilter,
		arg.NotificationIDFilter,
		arg.StatusFilter,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDeliveryLog{}
	for rows.Next() {
		var i NotificationDeliveryLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.NotificationID,
			&i.ParentAccountID,
			&i.MessageKind,
			&i.TemplateID,
			&i.Status,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.SentAt,
			&i.NextRetryAt,
			&i.DeliveryError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationOutbox = `-- name: ListNotificationOutbox :many
SELECT id, organization_id, event_type, aggregate_type, aggregate_id,
       notification_id, status, attempts, available_at, locked_at, processed_at,
       last_error, created_at, updated_at
FROM outbox_events
WHERE status IN ('pending', 'failed')
  AND available_at <= ?
  AND (locked_at IS NULL OR locked_at <= ?)
ORDER BY id
LIMIT ?
`

type ListNotificationOutboxParams struct {
	AvailableAt time.Time    `json:"available_at"`
	LockedAt    sql.NullTime `json:"locked_at"`
	Limit       int32        `json:"limit"`
}

type ListNotificationOutboxRow struct {
	ID             uint64       `json:"id"`
	OrganizationID uint64       `json:"organization_id"`
	EventType      string       `json:"event_type"`
	AggregateType  string       `json:"aggregate_type"`
	AggregateID    uint64       `json:"aggregate_id"`
	NotificationID uint64       `json:"notification_id"`
	Status         string       `json:"status"`
	Attempts       uint32       `json:"attempts"`
	AvailableAt    time.Time    `json:"available_at"`
	LockedAt       sql.NullTime `json:"locked_at"`
	ProcessedAt    sql.NullTime `json:"processed_at"`
	LastError      string       `json:"last_error"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
}

func (q *Queries) ListNotificationOutbox(ctx context.Context, arg ListNotificationOutboxParams) ([]ListNotificationOutboxRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationOutbox, arg.AvailableAt, arg.LockedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationOutboxRow{}
	for rows.Next() {
		var i ListNotificationOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.NotificationID,
			&i.Status,
			&i.Attempts,
			&i.AvailableAt,
			&i.LockedAt,
			&i.ProcessedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryNotificationOutbox = `-- name: RetryNotificationOutbox :execresult
UPDATE outbox_events
SET status = 'pending', attempts = 0, available_at = CURRENT_TIMESTAMP(3),
    locked_at = NULL, processed_at = NULL, last_error = '', updated_at = CURRENT_TIMESTAMP(3)
WHERE notification_id = ? AND organization_id = ? AND status = 'failed'
`

type RetryNotificationOutboxParams struct {
	NotificationID uint64 `json:"notification_id"`
	OrganizationID uint64 `json:"organization_id"`
}

func (q *Queries) RetryNotificationOutbox(ctx context.Context, arg RetryNotificationOutboxParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, retryNotificationOutbox, arg.NotificationID, arg.OrganizationID)
}

const updateNotificationDeliveryLogStatus = `-- name: UpdateNotificationDeliveryLogStatus :execresult
UPDATE notification_delivery_logs
SET status = ?, attempts = ?, last_attempt_at = ?, sent_at = ?, next_retry_at = ?,
    delivery_error = ?, updated_at = CURRENT_TIMESTAMP(3)
WHERE id = ? AND organization_id = ?
`

type UpdateNotificationDeliveryLogStatusParams struct {
	Status         string       `json:"status"`
	Attempts       uint32       `json:"attempts"`
	LastAttemptAt  sql.NullTime `json:"last_attempt_at"`
	SentAt         sql.NullTime `json:"sent_at"`
	NextRetryAt    sql.NullTime `json:"next_retry_at"`
	DeliveryError  string       `json:"delivery_error"`
	ID             uint64       `json:"id"`
	OrganizationID uint64       `json:"organization_id"`
}

func (q *Queries) UpdateNotificationDeliveryLogStatus(ctx context.Context, arg UpdateNotificationDeliveryLogStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateNotificationDeliveryLogStatus,
		arg.Status,
		arg.Attempts,
		arg.LastAttemptAt,
		arg.SentAt,
		arg.NextRetryAt,
		arg.DeliveryError,
		arg.ID,
		arg.OrganizationID,
	)
}
