// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parent_and_leave.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const cancelParentLeaveRequest = `-- name: CancelParentLeaveRequest :execresult
UPDATE leave_requests
SET status = 'cancelled', updated_at = CURRENT_TIMESTAMP(3)
WHERE id = ? AND organization_id = ? AND parent_account_id = ? AND status = 'pending'
`

type CancelParentLeaveRequestParams struct {
	ID              uint64        `json:"id"`
	OrganizationID  uint64        `json:"organization_id"`
	ParentAccountID sql.NullInt64 `json:"parent_account_id"`
}

func (q *Queries) CancelParentLeaveRequest(ctx context.Context, arg CancelParentLeaveRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, cancelParentLeaveRequest, arg.ID, arg.OrganizationID, arg.ParentAccountID)
}

const createLeaveRequest = `-- name: CreateLeaveRequest :execresult
INSERT INTO leave_requests (
    organization_id, student_id, parent_account_id, submitted_by_type,
    submitted_by_user_id, leave_date, reason, status
) VALUES (?, ?, ?, ?, ?, ?, ?, 'pending')
`

type CreateLeaveRequestParams struct {
	OrganizationID    uint64        `json:"organization_id"`
	StudentID         uint64        `json:"student_id"`
	ParentAccountID   sql.NullInt64 `json:"parent_account_id"`
	SubmittedByType   string        `json:"submitted_by_type"`
	SubmittedByUserID sql.NullInt64 `json:"submitted_by_user_id"`
	LeaveDate         time.Time     `json:"leave_date"`
	Reason            string        `json:"reason"`
}

func (q *Queries) CreateLeaveRequest(ctx context.Context, arg CreateLeaveRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLeaveRequest,
		arg.OrganizationID,
		arg.StudentID,
		arg.ParentAccountID,
		arg.SubmittedByType,
		arg.SubmittedByUserID,
		arg.LeaveDate,
		arg.Reason,
	)
}

const createParentAccount = `-- name: CreateParentAccount :execresult
INSERT INTO parent_accounts (organization_id, openid, nickname, avatar, status)
VALUES (?, ?, ?, ?, 'active')
`

type CreateParentAccountParams struct {
	OrganizationID uint64 `json:"organization_id"`
	Openid         string `json:"openid"`
	Nickname       string `json:"nickname"`
	Avatar         string `json:"avatar"`
}

func (q *Queries) CreateParentAccount(ctx context.Context, arg CreateParentAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createParentAccount,
		arg.OrganizationID,
		arg.Openid,
		arg.Nickname,
		arg.Avatar,
	)
}

const createParentStudentBinding = `-- name: CreateParentStudentBinding :execresult
INSERT INTO parent_student_bindings (
    organization_id, parent_account_id, student_id, relationship, is_primary, status
) VALUES (?, ?, ?, ?, ?, 'active')
`

type CreateParentStudentBindingParams struct {
	OrganizationID  uint64 `json:"organization_id"`
	ParentAccountID uint64 `json:"parent_account_id"`
	StudentID       uint64 `json:"student_id"`
	Relationship    string `json:"relationship"`
	IsPrimary       bool   `json:"is_primary"`
}

func (q *Queries) CreateParentStudentBinding(ctx context.Context, arg CreateParentStudentBindingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createParentStudentBinding,
		arg.OrganizationID,
		arg.ParentAccountID,
		arg.StudentID,
		arg.Relationship,
		arg.IsPrimary,
	)
}

const createTeacherLeaveRequest = `-- name: CreateTeacherLeaveRequest :execresult
INSERT INTO leave_requests (
    organization_id, student_id, parent_account_id, submitted_by_type,
    submitted_by_user_id, leave_date, reason, status, teacher_note,
    reviewed_by_user_id, reviewed_at
) VALUES (?, ?, NULL, 'teacher', ?, ?, ?, 'approved', '老师口头代记', ?, CURRENT_TIMESTAMP(3))
`

type CreateTeacherLeaveRequestParams struct {
	OrganizationID    uint64        `json:"organization_id"`
	StudentID         uint64        `json:"student_id"`
	SubmittedByUserID sql.NullInt64 `json:"submitted_by_user_id"`
	LeaveDate         time.Time     `json:"leave_date"`
	Reason            string        `json:"reason"`
	ReviewedByUserID  sql.NullInt64 `json:"reviewed_by_user_id"`
}

func (q *Queries) CreateTeacherLeaveRequest(ctx context.Context, arg CreateTeacherLeaveRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTeacherLeaveRequest,
		arg.OrganizationID,
		arg.StudentID,
		arg.SubmittedByUserID,
		arg.LeaveDate,
		arg.Reason,
		arg.ReviewedByUserID,
	)
}

const findActiveTeacherLeaveRequest = `-- name: FindActiveTeacherLeaveRequest :one
SELECT id, organization_id, student_id, parent_account_id, submitted_by_type,
       submitted_by_user_id, leave_date, reason, status, teacher_note,
       reviewed_by_user_id, reviewed_at, created_at, updated_at
FROM leave_requests
WHERE organization_id = ? AND student_id = ? AND leave_date = ?
  AND status IN ('pending', 'approved')
ORDER BY id DESC
LIMIT 1
`

type FindActiveTeacherLeaveRequestParams struct {
	OrganizationID uint64    `json:"organization_id"`
	StudentID      uint64    `json:"student_id"`
	LeaveDate      time.Time `json:"leave_date"`
}

func (q *Queries) FindActiveTeacherLeaveRequest(ctx context.Context, arg FindActiveTeacherLeaveRequestParams) (LeaveRequest, error) {
	row := q.db.QueryRowContext(ctx, findActiveTeacherLeaveRequest, arg.OrganizationID, arg.StudentID, arg.LeaveDate)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StudentID,
		&i.ParentAccountID,
		&i.SubmittedByType,
		&i.SubmittedByUserID,
		&i.LeaveDate,
		&i.Reason,
		&i.Status,
		&i.TeacherNote,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestParentPrivacyConsent = `-- name: GetLatestParentPrivacyConsent :one
SELECT id, organization_id, parent_account_id, policy_version, consented_at, created_at
FROM parent_privacy_consents
WHERE organization_id = ? AND parent_account_id = ?
ORDER BY consented_at DESC, id DESC
LIMIT 1
`

type GetLatestParentPrivacyConsentParams struct {
	OrganizationID  uint64 `json:"organization_id"`
	ParentAccountID uint64 `json:"parent_account_id"`
}

func (q *Queries) GetLatestParentPrivacyConsent(ctx context.Context, arg GetLatestParentPrivacyConsentParams) (ParentPrivacyConsent, error) {
	row := q.db.QueryRowContext(ctx, getLatestParentPrivacyConsent, arg.OrganizationID, arg.ParentAccountID)
	var i ParentPrivacyConsent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentAccountID,
		&i.PolicyVersion,
		&i.ConsentedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLeaveRequestByID = `-- name: GetLeaveRequestByID :one
SELECT id, organization_id, student_id, parent_account_id, submitted_by_type,
       submitted_by_user_id, leave_date, reason, status, teacher_note,
       reviewed_by_user_id, reviewed_at, created_at, updated_at
FROM leave_requests
WHERE id = ? AND organization_id = ?
LIMIT 1
`

type GetLeaveRequestByIDParams struct {
	ID             uint64 `json:"id"`
	OrganizationID uint64 `json:"organization_id"`
}

func (q *Queries) GetLeaveRequestByID(ctx context.Context, arg GetLeaveRequestByIDParams) (LeaveRequest, error) {
	row := q.db.QueryRowContext(ctx, getLeaveRequestByID, arg.ID, arg.OrganizationID)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StudentID,
		&i.ParentAccountID,
		&i.SubmittedByType,
		&i.SubmittedByUserID,
		&i.LeaveDate,
		&i.Reason,
		&i.Status,
		&i.TeacherNote,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParentAccountByID = `-- name: GetParentAccountByID :one
SELECT id, organization_id, openid, nickname, avatar, status, created_at, updated_at
FROM parent_accounts
WHERE id = ? AND organization_id = ?
LIMIT 1
`

type GetParentAccountByIDParams struct {
	ID             uint64 `json:"id"`
	OrganizationID uint64 `json:"organization_id"`
}

func (q *Queries) GetParentAccountByID(ctx context.Context, arg GetParentAccountByIDParams) (ParentAccount, error) {
	row := q.db.QueryRowContext(ctx, getParentAccountByID, arg.ID, arg.OrganizationID)
	var i ParentAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Openid,
		&i.Nickname,
		&i.Avatar,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParentAccountByOpenID = `-- name: GetParentAccountByOpenID :one
SELECT id, organization_id, openid, nickname, avatar, status, created_at, updated_at
FROM parent_accounts
WHERE openid = ? AND organization_id = ?
LIMIT 1
`

type GetParentAccountByOpenIDParams struct {
	Openid         string `json:"openid"`
	OrganizationID uint64 `json:"organization_id"`
}

func (q *Queries) GetParentAccountByOpenID(ctx context.Context, arg GetParentAccountByOpenIDParams) (ParentAccount, error) {
	row := q.db.QueryRowContext(ctx, getParentAccountByOpenID, arg.Openid, arg.OrganizationID)
	var i ParentAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Openid,
		&i.Nickname,
		&i.Avatar,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllLeaveRequests = `-- name: ListAllLeaveRequests :many
SELECT id, organization_id, student_id, parent_account_id, submitted_by_type,
       submitted_by_user_id, leave_date, reason, status, teacher_note,
       reviewed_by_user_id, reviewed_at, created_at, updated_at
FROM leave_requests
WHERE organization_id = ?
ORDER BY leave_date DESC, id DESC
`

func (q *Queries) ListAllLeaveRequests(ctx context.Context, organizationID uint64) ([]LeaveRequest, error) {
	rows, err := q.db.QueryContext(ctx, listAllLeaveRequests, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaveRequest{}
	for rows.Next() {
		var i LeaveRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StudentID,
			&i.ParentAccountID,
			&i.SubmittedByType,
			&i.SubmittedByUserID,
			&i.LeaveDate,
			&i.Reason,
			&i.Status,
			&i.TeacherNote,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovedLeaveStudentIDs = `-- name: ListApprovedLeaveStudentIDs :many
SELECT student_id
FROM leave_requests
WHERE organization_id = ? AND leave_date = ? AND status = 'approved'
`

type ListApprovedLeaveStudentIDsParams struct {
	OrganizationID uint64    `json:"organization_id"`
	LeaveDate      time.Time `json:"leave_date"`
}

func (q *Queries) ListApprovedLeaveStudentIDs(ctx context.Context, arg ListApprovedLeaveStudentIDsParams) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, listApprovedLeaveStudentIDs, arg.OrganizationID, arg.LeaveDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var student_id uint64
		if err := rows.Scan(&student_id); err != nil {
			return nil, err
		}
		items = append(items, student_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentAccountsForStudent = `-- name: ListParentAccountsForStudent :many
SELECT p.id, p.organization_id, p.openid, p.nickname, p.avatar, p.status,
       p.created_at, p.updated_at
FROM parent_accounts p
JOIN parent_student_bindings b ON b.parent_account_id = p.id
WHERE b.organization_id = ? AND b.student_id = ?
  AND b.status = 'active' AND p.status = 'active'
ORDER BY p.id
`

type ListParentAccountsForStudentParams struct {
	OrganizationID uint64 `json:"organization_id"`
	StudentID      uint64 `json:"student_id"`
}

func (q *Queries) ListParentAccountsForStudent(ctx context.Context, arg ListParentAccountsForStudentParams) ([]ParentAccount, error) {
	rows, err := q.db.QueryContext(ctx, listParentAccountsForStudent, arg.OrganizationID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParentAccount{}
	for rows.Next() {
		var i ParentAccount
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Openid,
			&i.Nickname,
			&i.Avatar,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentLeaveRequests = `-- name: ListParentLeaveRequests :many
SELECT id, organization_id, student_id, parent_account_id, submitted_by_type,
       submitted_by_user_id, leave_date, reason, status, teacher_note,
       reviewed_by_user_id, reviewed_at, created_at, updated_at
FROM leave_requests
WHERE organization_id = ? AND parent_account_id = ?
ORDER BY leave_date DESC, id DESC
`

type ListParentLeaveRequestsParams struct {
	OrganizationID  uint64        `json:"organization_id"`
	ParentAccountID sql.NullInt64 `json:"parent_account_id"`
}

func (q *Queries) ListParentLeaveRequests(ctx context.Context, arg ListParentLeaveRequestsParams) ([]LeaveRequest, error) {
	rows, err := q.db.QueryContext(ctx, listParentLeaveRequests, arg.OrganizationID, arg.ParentAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaveRequest{}
	for rows.Next() {
		var i LeaveRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StudentID,
			&i.ParentAccountID,
			&i.SubmittedByType,
			&i.SubmittedByUserID,
			&i.LeaveDate,
			&i.Reason,
			&i.Status,
			&i.TeacherNote,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentMessageSubscriptions = `-- name: ListParentMessageSubscriptions :many
SELECT parent_account_id, message_kind, status, template_version, authorized_at, updated_at
FROM parent_message_subscriptions
WHERE organization_id = ? AND parent_account_id = ?
ORDER BY message_kind
`

type ListParentMessageSubscriptionsParams struct {
	OrganizationID  uint64 `json:"organization_id"`
	ParentAccountID uint64 `json:"parent_account_id"`
}

type ListParentMessageSubscriptionsRow struct {
	ParentAccountID uint64       `json:"parent_account_id"`
	MessageKind     string       `json:"message_kind"`
	Status          string       `json:"status"`
	TemplateVersion string       `json:"template_version"`
	AuthorizedAt    sql.NullTime `json:"authorized_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

func (q *Queries) ListParentMessageSubscriptions(ctx context.Context, arg ListParentMessageSubscriptionsParams) ([]ListParentMessageSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listParentMessageSubscriptions, arg.OrganizationID, arg.ParentAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParentMessageSubscriptionsRow{}
	for rows.Next() {
		var i ListParentMessageSubscriptionsRow
		if err := rows.Scan(
			&i.ParentAccountID,
			&i.MessageKind,
			&i.Status,
			&i.TemplateVersion,
			&i.AuthorizedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentStudentBindings = `-- name: ListParentStudentBindings :many
SELECT b.id AS binding_id, b.organization_id, b.parent_account_id, b.student_id,
       s.name AS student_name, s.school_class_id, s.care_class_id,
       b.relationship, b.is_primary, b.status, b.created_at, b.updated_at
FROM parent_student_bindings b
JOIN students s ON s.id = b.student_id
WHERE b.parent_account_id = ? AND b.organization_id = ? AND b.status = 'active'
ORDER BY s.name, b.student_id
`

type ListParentStudentBindingsParams struct {
	ParentAccountID uint64 `json:"parent_account_id"`
	OrganizationID  uint64 `json:"organization_id"`
}

type ListParentStudentBindingsRow struct {
	BindingID       uint64        `json:"binding_id"`
	OrganizationID  uint64        `json:"organization_id"`
	ParentAccountID uint64        `json:"parent_account_id"`
	StudentID       uint64        `json:"student_id"`
	StudentName     string        `json:"student_name"`
	SchoolClassID   uint64        `json:"school_class_id"`
	CareClassID     sql.NullInt64 `json:"care_class_id"`
	Relationship    string        `json:"relationship"`
	IsPrimary       bool          `json:"is_primary"`
	Status          string        `json:"status"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

func (q *Queries) ListParentStudentBindings(ctx context.Context, arg ListParentStudentBindingsParams) ([]ListParentStudentBindingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listParentStudentBindings, arg.ParentAccountID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParentStudentBindingsRow{}
	for rows.Next() {
		var i ListParentStudentBindingsRow
		if err := rows.Scan(
			&i.BindingID,
			&i.OrganizationID,
			&i.ParentAccountID,
			&i.StudentID,
			&i.StudentName,
			&i.SchoolClassID,
			&i.CareClassID,
			&i.Relationship,
			&i.IsPrimary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordParentPrivacyConsent = `-- name: RecordParentPrivacyConsent :execresult
INSERT INTO parent_privacy_consents (
    organization_id, parent_account_id, policy_version, consented_at
) VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE policy_version = VALUES(policy_version)
`

type RecordParentPrivacyConsentParams struct {
	OrganizationID  uint64    `json:"organization_id"`
	ParentAccountID uint64    `json:"parent_account_id"`
	PolicyVersion   string    `json:"policy_version"`
	ConsentedAt     time.Time `json:"consented_at"`
}

func (q *Queries) RecordParentPrivacyConsent(ctx context.Context, arg RecordParentPrivacyConsentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, recordParentPrivacyConsent,
		arg.OrganizationID,
		arg.ParentAccountID,
		arg.PolicyVersion,
		arg.ConsentedAt,
	)
}

const reviewLeaveRequest = `-- name: ReviewLeaveRequest :execresult
UPDATE leave_requests
SET status = ?, teacher_note = ?, reviewed_by_user_id = ?, reviewed_at = ?
WHERE id = ? AND organization_id = ? AND status = 'pending'
`

type ReviewLeaveRequestParams struct {
	Status           string        `json:"status"`
	TeacherNote      string        `json:"teacher_note"`
	ReviewedByUserID sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt       sql.NullTime  `json:"reviewed_at"`
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
}

func (q *Queries) ReviewLeaveRequest(ctx context.Context, arg ReviewLeaveRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, reviewLeaveRequest,
		arg.Status,
		arg.TeacherNote,
		arg.ReviewedByUserID,
		arg.ReviewedAt,
		arg.ID,
		arg.OrganizationID,
	)
}

const updateParentLeaveRequest = `-- name: UpdateParentLeaveRequest :execresult
UPDATE leave_requests
SET leave_date = ?, reason = ?, updated_at = CURRENT_TIMESTAMP(3)
WHERE id = ? AND organization_id = ? AND parent_account_id = ? AND status = 'pending'
`

type UpdateParentLeaveRequestParams struct {
	LeaveDate       time.Time     `json:"leave_date"`
	Reason          string        `json:"reason"`
	ID              uint64        `json:"id"`
	OrganizationID  uint64        `json:"organization_id"`
	ParentAccountID sql.NullInt64 `json:"parent_account_id"`
}

func (q *Queries) UpdateParentLeaveRequest(ctx context.Context, arg UpdateParentLeaveRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateParentLeaveRequest,
		arg.LeaveDate,
		arg.Reason,
		arg.ID,
		arg.OrganizationID,
		arg.ParentAccountID,
	)
}

const upsertParentMessageSubscription = `-- name: UpsertParentMessageSubscription :execresult
INSERT INTO parent_message_subscriptions (
    organization_id, parent_account_id, message_kind, status, template_version,
    authorized_at
) VALUES (?, ?, ?, ?, ?, CASE WHEN ? = 'accept' THEN CURRENT_TIMESTAMP(3) ELSE NULL END)
ON DUPLICATE KEY UPDATE
    status = VALUES(status),
    template_version = VALUES(template_version),
    authorized_at = CASE WHEN VALUES(status) = 'accept' THEN CURRENT_TIMESTAMP(3) ELSE authorized_at END,
    updated_at = CURRENT_TIMESTAMP(3)
`

type UpsertParentMessageSubscriptionParams struct {
	OrganizationID  uint64 `json:"organization_id"`
	ParentAccountID uint64 `json:"parent_account_id"`
	MessageKind     string `json:"message_kind"`
	Status          string `json:"status"`
	TemplateVersion string `json:"template_version"`
}

func (q *Queries) UpsertParentMessageSubscription(ctx context.Context, arg UpsertParentMessageSubscriptionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertParentMessageSubscription,
		arg.OrganizationID,
		arg.ParentAccountID,
		arg.MessageKind,
		arg.Status,
		arg.TemplateVersion,
		arg.Status,
	)
}
