// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parent_child_applications.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createParentChildApplication = `-- name: CreateParentChildApplication :execresult
INSERT INTO parent_child_applications (
    organization_id, parent_account_id, student_name,
    school_name_input, grade_input, class_name_input,
    school_id, school_class_id, grade, class_name,
    guardian_name, guardian_phone, relationship, notes, status
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending')
`

type CreateParentChildApplicationParams struct {
	OrganizationID  uint64        `json:"organization_id"`
	ParentAccountID uint64        `json:"parent_account_id"`
	StudentName     string        `json:"student_name"`
	SchoolNameInput string        `json:"school_name_input"`
	GradeInput      string        `json:"grade_input"`
	ClassNameInput  string        `json:"class_name_input"`
	SchoolID        sql.NullInt64 `json:"school_id"`
	SchoolClassID   sql.NullInt64 `json:"school_class_id"`
	Grade           string        `json:"grade"`
	ClassName       string        `json:"class_name"`
	GuardianName    string        `json:"guardian_name"`
	GuardianPhone   string        `json:"guardian_phone"`
	Relationship    string        `json:"relationship"`
	Notes           string        `json:"notes"`
}

func (q *Queries) CreateParentChildApplication(ctx context.Context, arg CreateParentChildApplicationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createParentChildApplication,
		arg.OrganizationID,
		arg.ParentAccountID,
		arg.StudentName,
		arg.SchoolNameInput,
		arg.GradeInput,
		arg.ClassNameInput,
		arg.SchoolID,
		arg.SchoolClassID,
		arg.Grade,
		arg.ClassName,
		arg.GuardianName,
		arg.GuardianPhone,
		arg.Relationship,
		arg.Notes,
	)
}

const getParentChildApplication = `-- name: GetParentChildApplication :one
SELECT id, organization_id, parent_account_id, student_id,
       student_name, school_name_input, grade_input, class_name_input,
       school_id, school_class_id, grade, class_name,
       guardian_name, guardian_phone, relationship, notes,
       status, review_note, reviewed_by_user_id, reviewed_at,
       created_at, updated_at
FROM parent_child_applications
WHERE id = ? AND organization_id = ?
LIMIT 1
`

type GetParentChildApplicationParams struct {
	ID             uint64 `json:"id"`
	OrganizationID uint64 `json:"organization_id"`
}

type GetParentChildApplicationRow struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	ParentAccountID  uint64        `json:"parent_account_id"`
	StudentID        sql.NullInt64 `json:"student_id"`
	StudentName      string        `json:"student_name"`
	SchoolNameInput  string        `json:"school_name_input"`
	GradeInput       string        `json:"grade_input"`
	ClassNameInput   string        `json:"class_name_input"`
	SchoolID         sql.NullInt64 `json:"school_id"`
	SchoolClassID    sql.NullInt64 `json:"school_class_id"`
	Grade            string        `json:"grade"`
	ClassName        string        `json:"class_name"`
	GuardianName     string        `json:"guardian_name"`
	GuardianPhone    string        `json:"guardian_phone"`
	Relationship     string        `json:"relationship"`
	Notes            string        `json:"notes"`
	Status           string        `json:"status"`
	ReviewNote       string        `json:"review_note"`
	ReviewedByUserID sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt       sql.NullTime  `json:"reviewed_at"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

func (q *Queries) GetParentChildApplication(ctx context.Context, arg GetParentChildApplicationParams) (GetParentChildApplicationRow, error) {
	row := q.db.QueryRowContext(ctx, getParentChildApplication, arg.ID, arg.OrganizationID)
	var i GetParentChildApplicationRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentAccountID,
		&i.StudentID,
		&i.StudentName,
		&i.SchoolNameInput,
		&i.GradeInput,
		&i.ClassNameInput,
		&i.SchoolID,
		&i.SchoolClassID,
		&i.Grade,
		&i.ClassName,
		&i.GuardianName,
		&i.GuardianPhone,
		&i.Relationship,
		&i.Notes,
		&i.Status,
		&i.ReviewNote,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllParentChildApplications = `-- name: ListAllParentChildApplications :many
SELECT id, organization_id, parent_account_id, student_id,
       student_name, school_name_input, grade_input, class_name_input,
       school_id, school_class_id, grade, class_name,
       guardian_name, guardian_phone, relationship, notes,
       status, review_note, reviewed_by_user_id, reviewed_at,
       created_at, updated_at
FROM parent_child_applications
WHERE organization_id = ?
ORDER BY created_at DESC, id DESC
`

type ListAllParentChildApplicationsRow struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	ParentAccountID  uint64        `json:"parent_account_id"`
	StudentID        sql.NullInt64 `json:"student_id"`
	StudentName      string        `json:"student_name"`
	SchoolNameInput  string        `json:"school_name_input"`
	GradeInput       string        `json:"grade_input"`
	ClassNameInput   string        `json:"class_name_input"`
	SchoolID         sql.NullInt64 `json:"school_id"`
	SchoolClassID    sql.NullInt64 `json:"school_class_id"`
	Grade            string        `json:"grade"`
	ClassName        string        `json:"class_name"`
	GuardianName     string        `json:"guardian_name"`
	GuardianPhone    string        `json:"guardian_phone"`
	Relationship     string        `json:"relationship"`
	Notes            string        `json:"notes"`
	Status           string        `json:"status"`
	ReviewNote       string        `json:"review_note"`
	ReviewedByUserID sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt       sql.NullTime  `json:"reviewed_at"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

func (q *Queries) ListAllParentChildApplications(ctx context.Context, organizationID uint64) ([]ListAllParentChildApplicationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllParentChildApplications, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllParentChildApplicationsRow{}
	for rows.Next() {
		var i ListAllParentChildApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ParentAccountID,
			&i.StudentID,
			&i.StudentName,
			&i.SchoolNameInput,
			&i.GradeInput,
			&i.ClassNameInput,
			&i.SchoolID,
			&i.SchoolClassID,
			&i.Grade,
			&i.ClassName,
			&i.GuardianName,
			&i.GuardianPhone,
			&i.Relationship,
			&i.Notes,
			&i.Status,
			&i.ReviewNote,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentChildApplications = `-- name: ListParentChildApplications :many
SELECT id, organization_id, parent_account_id, student_id,
       student_name, school_name_input, grade_input, class_name_input,
       school_id, school_class_id, grade, class_name,
       guardian_name, guardian_phone, relationship, notes,
       status, review_note, reviewed_by_user_id, reviewed_at,
       created_at, updated_at
FROM parent_child_applications
WHERE organization_id = ? AND parent_account_id = ?
ORDER BY created_at DESC, id DESC
`

type ListParentChildApplicationsParams struct {
	OrganizationID  uint64 `json:"organization_id"`
	ParentAccountID uint64 `json:"parent_account_id"`
}

type ListParentChildApplicationsRow struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	ParentAccountID  uint64        `json:"parent_account_id"`
	StudentID        sql.NullInt64 `json:"student_id"`
	StudentName      string        `json:"student_name"`
	SchoolNameInput  string        `json:"school_name_input"`
	GradeInput       string        `json:"grade_input"`
	ClassNameInput   string        `json:"class_name_input"`
	SchoolID         sql.NullInt64 `json:"school_id"`
	SchoolClassID    sql.NullInt64 `json:"school_class_id"`
	Grade            string        `json:"grade"`
	ClassName        string        `json:"class_name"`
	GuardianName     string        `json:"guardian_name"`
	GuardianPhone    string        `json:"guardian_phone"`
	Relationship     string        `json:"relationship"`
	Notes            string        `json:"notes"`
	Status           string        `json:"status"`
	ReviewNote       string        `json:"review_note"`
	ReviewedByUserID sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt       sql.NullTime  `json:"reviewed_at"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

func (q *Queries) ListParentChildApplications(ctx context.Context, arg ListParentChildApplicationsParams) ([]ListParentChildApplicationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listParentChildApplications, arg.OrganizationID, arg.ParentAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParentChildApplicationsRow{}
	for rows.Next() {
		var i ListParentChildApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ParentAccountID,
			&i.StudentID,
			&i.StudentName,
			&i.SchoolNameInput,
			&i.GradeInput,
			&i.ClassNameInput,
			&i.SchoolID,
			&i.SchoolClassID,
			&i.Grade,
			&i.ClassName,
			&i.GuardianName,
			&i.GuardianPhone,
			&i.Relationship,
			&i.Notes,
			&i.Status,
			&i.ReviewNote,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewParentChildApplication = `-- name: ReviewParentChildApplication :execresult
UPDATE parent_child_applications
SET status = ?, student_id = ?, school_id = ?, school_class_id = ?,
    review_note = ?, reviewed_by_user_id = ?, reviewed_at = ?
WHERE id = ? AND organization_id = ? AND status IN ('pending', 'needs_info')
`

type ReviewParentChildApplicationParams struct {
	Status           string        `json:"status"`
	StudentID        sql.NullInt64 `json:"student_id"`
	SchoolID         sql.NullInt64 `json:"school_id"`
	SchoolClassID    sql.NullInt64 `json:"school_class_id"`
	ReviewNote       string        `json:"review_note"`
	ReviewedByUserID sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt       sql.NullTime  `json:"reviewed_at"`
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
}

func (q *Queries) ReviewParentChildApplication(ctx context.Context, arg ReviewParentChildApplicationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, reviewParentChildApplication,
		arg.Status,
		arg.StudentID,
		arg.SchoolID,
		arg.SchoolClassID,
		arg.ReviewNote,
		arg.ReviewedByUserID,
		arg.ReviewedAt,
		arg.ID,
		arg.OrganizationID,
	)
}

const updateParentChildApplication = `-- name: UpdateParentChildApplication :execresult
UPDATE parent_child_applications
SET student_name = ?, school_name_input = ?, grade_input = ?, class_name_input = ?,
    school_id = ?, school_class_id = ?, grade = ?, class_name = ?,
    guardian_name = ?, guardian_phone = ?, relationship = ?, notes = ?,
    student_id = NULL, status = 'pending', review_note = '',
    reviewed_by_user_id = NULL, reviewed_at = NULL, updated_at = CURRENT_TIMESTAMP(3)
WHERE id = ? AND organization_id = ? AND parent_account_id = ? AND status = 'needs_info'
`

type UpdateParentChildApplicationParams struct {
	StudentName     string        `json:"student_name"`
	SchoolNameInput string        `json:"school_name_input"`
	GradeInput      string        `json:"grade_input"`
	ClassNameInput  string        `json:"class_name_input"`
	SchoolID        sql.NullInt64 `json:"school_id"`
	SchoolClassID   sql.NullInt64 `json:"school_class_id"`
	Grade           string        `json:"grade"`
	ClassName       string        `json:"class_name"`
	GuardianName    string        `json:"guardian_name"`
	GuardianPhone   string        `json:"guardian_phone"`
	Relationship    string        `json:"relationship"`
	Notes           string        `json:"notes"`
	ID              uint64        `json:"id"`
	OrganizationID  uint64        `json:"organization_id"`
	ParentAccountID uint64        `json:"parent_account_id"`
}

func (q *Queries) UpdateParentChildApplication(ctx context.Context, arg UpdateParentChildApplicationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateParentChildApplication,
		arg.StudentName,
		arg.SchoolNameInput,
		arg.GradeInput,
		arg.ClassNameInput,
		arg.SchoolID,
		arg.SchoolClassID,
		arg.Grade,
		arg.ClassName,
		arg.GuardianName,
		arg.GuardianPhone,
		arg.Relationship,
		arg.Notes,
		arg.ID,
		arg.OrganizationID,
		arg.ParentAccountID,
	)
}
