// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pickup_schedules.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createPickupSchedule = `-- name: CreatePickupSchedule :execresult
INSERT INTO pickup_schedules (
    organization_id, school_id, school_class_id, care_class_id, weekday,
    pickup_mode, teacher_user_id, teacher_name, expected_pickup_time,
    effective_from, effective_to, enabled, notes
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePickupScheduleParams struct {
	OrganizationID     uint64        `json:"organization_id"`
	SchoolID           uint64        `json:"school_id"`
	SchoolClassID      uint64        `json:"school_class_id"`
	CareClassID        sql.NullInt64 `json:"care_class_id"`
	Weekday            uint8         `json:"weekday"`
	PickupMode         string        `json:"pickup_mode"`
	TeacherUserID      sql.NullInt64 `json:"teacher_user_id"`
	TeacherName        string        `json:"teacher_name"`
	ExpectedPickupTime string        `json:"expected_pickup_time"`
	EffectiveFrom      time.Time     `json:"effective_from"`
	EffectiveTo        sql.NullTime  `json:"effective_to"`
	Enabled            bool          `json:"enabled"`
	Notes              string        `json:"notes"`
}

func (q *Queries) CreatePickupSchedule(ctx context.Context, arg CreatePickupScheduleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPickupSchedule,
		arg.OrganizationID,
		arg.SchoolID,
		arg.SchoolClassID,
		arg.CareClassID,
		arg.Weekday,
		arg.PickupMode,
		arg.TeacherUserID,
		arg.TeacherName,
		arg.ExpectedPickupTime,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.Enabled,
		arg.Notes,
	)
}

const getPickupScheduleByID = `-- name: GetPickupScheduleByID :one
SELECT id, organization_id, school_id, school_class_id, care_class_id,
       weekday, pickup_mode, teacher_user_id, teacher_name, expected_pickup_time,
       effective_from, effective_to, enabled, notes, created_at, updated_at
FROM pickup_schedules
WHERE id = ? AND organization_id = ?
LIMIT 1
`

type GetPickupScheduleByIDParams struct {
	ID             uint64 `json:"id"`
	OrganizationID uint64 `json:"organization_id"`
}

func (q *Queries) GetPickupScheduleByID(ctx context.Context, arg GetPickupScheduleByIDParams) (PickupSchedule, error) {
	row := q.db.QueryRowContext(ctx, getPickupScheduleByID, arg.ID, arg.OrganizationID)
	var i PickupSchedule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SchoolID,
		&i.SchoolClassID,
		&i.CareClassID,
		&i.Weekday,
		&i.PickupMode,
		&i.TeacherUserID,
		&i.TeacherName,
		&i.ExpectedPickupTime,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Enabled,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPickupSchedules = `-- name: ListPickupSchedules :many
SELECT id, organization_id, school_id, school_class_id, care_class_id,
       weekday, pickup_mode, teacher_user_id, teacher_name, expected_pickup_time,
       effective_from, effective_to, enabled, notes, created_at, updated_at
FROM pickup_schedules
WHERE organization_id = ?
ORDER BY enabled DESC, weekday ASC, expected_pickup_time ASC, id DESC
`

func (q *Queries) ListPickupSchedules(ctx context.Context, organizationID uint64) ([]PickupSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listPickupSchedules, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PickupSchedule{}
	for rows.Next() {
		var i PickupSchedule
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SchoolID,
			&i.SchoolClassID,
			&i.CareClassID,
			&i.Weekday,
			&i.PickupMode,
			&i.TeacherUserID,
			&i.TeacherName,
			&i.ExpectedPickupTime,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Enabled,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePickupSchedule = `-- name: UpdatePickupSchedule :execresult
UPDATE pickup_schedules
SET school_id = ?, school_class_id = ?, care_class_id = ?, weekday = ?,
    pickup_mode = ?, teacher_user_id = ?, teacher_name = ?, expected_pickup_time = ?,
    effective_from = ?, effective_to = ?, enabled = ?, notes = ?,
    updated_at = CURRENT_TIMESTAMP(3)
WHERE id = ? AND organization_id = ?
`

type UpdatePickupScheduleParams struct {
	SchoolID           uint64        `json:"school_id"`
	SchoolClassID      uint64        `json:"school_class_id"`
	CareClassID        sql.NullInt64 `json:"care_class_id"`
	Weekday            uint8         `json:"weekday"`
	PickupMode         string        `json:"pickup_mode"`
	TeacherUserID      sql.NullInt64 `json:"teacher_user_id"`
	TeacherName        string        `json:"teacher_name"`
	ExpectedPickupTime string        `json:"expected_pickup_time"`
	EffectiveFrom      time.Time     `json:"effective_from"`
	EffectiveTo        sql.NullTime  `json:"effective_to"`
	Enabled            bool          `json:"enabled"`
	Notes              string        `json:"notes"`
	ID                 uint64        `json:"id"`
	OrganizationID     uint64        `json:"organization_id"`
}

func (q *Queries) UpdatePickupSchedule(ctx context.Context, arg UpdatePickupScheduleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePickupSchedule,
		arg.SchoolID,
		arg.SchoolClassID,
		arg.CareClassID,
		arg.Weekday,
		arg.PickupMode,
		arg.TeacherUserID,
		arg.TeacherName,
		arg.ExpectedPickupTime,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.Enabled,
		arg.Notes,
		arg.ID,
		arg.OrganizationID,
	)
}
