// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pickup_handoffs.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createPickupHandoff = `-- name: CreatePickupHandoff :execresult
INSERT INTO pickup_operation_handoffs (
    organization_id, operation_id, from_teacher_user_id, from_teacher_name,
    to_teacher_user_id, to_teacher_name, teacher_role, note,
    handoff_at, created_by_user_id, created_by_name
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePickupHandoffParams struct {
	OrganizationID    uint64        `json:"organization_id"`
	OperationID       uint64        `json:"operation_id"`
	FromTeacherUserID sql.NullInt64 `json:"from_teacher_user_id"`
	FromTeacherName   string        `json:"from_teacher_name"`
	ToTeacherUserID   uint64        `json:"to_teacher_user_id"`
	ToTeacherName     string        `json:"to_teacher_name"`
	TeacherRole       string        `json:"teacher_role"`
	Note              string        `json:"note"`
	HandoffAt         time.Time     `json:"handoff_at"`
	CreatedByUserID   sql.NullInt64 `json:"created_by_user_id"`
	CreatedByName     string        `json:"created_by_name"`
}

func (q *Queries) CreatePickupHandoff(ctx context.Context, arg CreatePickupHandoffParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPickupHandoff,
		arg.OrganizationID,
		arg.OperationID,
		arg.FromTeacherUserID,
		arg.FromTeacherName,
		arg.ToTeacherUserID,
		arg.ToTeacherName,
		arg.TeacherRole,
		arg.Note,
		arg.HandoffAt,
		arg.CreatedByUserID,
		arg.CreatedByName,
	)
}

const handoffPickupOperation = `-- name: HandoffPickupOperation :execresult
UPDATE pickup_operations
SET executing_teacher_user_id = ?, executing_teacher_name = ?, teacher_role = ?, updated_at = CURRENT_TIMESTAMP(3)
WHERE id = ? AND organization_id = ? AND status = 'started'
`

type HandoffPickupOperationParams struct {
	ExecutingTeacherUserID sql.NullInt64 `json:"executing_teacher_user_id"`
	ExecutingTeacherName   string        `json:"executing_teacher_name"`
	TeacherRole            string        `json:"teacher_role"`
	ID                     uint64        `json:"id"`
	OrganizationID         uint64        `json:"organization_id"`
}

func (q *Queries) HandoffPickupOperation(ctx context.Context, arg HandoffPickupOperationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, handoffPickupOperation,
		arg.ExecutingTeacherUserID,
		arg.ExecutingTeacherName,
		arg.TeacherRole,
		arg.ID,
		arg.OrganizationID,
	)
}

const listPickupHandoffs = `-- name: ListPickupHandoffs :many
SELECT id, organization_id, operation_id, from_teacher_user_id, from_teacher_name,
       to_teacher_user_id, to_teacher_name, teacher_role, note, handoff_at,
       created_by_user_id, created_by_name
FROM pickup_operation_handoffs
WHERE organization_id = ? AND operation_id = ?
ORDER BY handoff_at DESC, id DESC
`

type ListPickupHandoffsParams struct {
	OrganizationID uint64 `json:"organization_id"`
	OperationID    uint64 `json:"operation_id"`
}

func (q *Queries) ListPickupHandoffs(ctx context.Context, arg ListPickupHandoffsParams) ([]PickupOperationHandoff, error) {
	rows, err := q.db.QueryContext(ctx, listPickupHandoffs, arg.OrganizationID, arg.OperationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PickupOperationHandoff{}
	for rows.Next() {
		var i PickupOperationHandoff
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OperationID,
			&i.FromTeacherUserID,
			&i.FromTeacherName,
			&i.ToTeacherUserID,
			&i.ToTeacherName,
			&i.TeacherRole,
			&i.Note,
			&i.HandoffAt,
			&i.CreatedByUserID,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
