// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pickup_operations.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const addPickupOperationStudent = `-- name: AddPickupOperationStudent :execresult
INSERT INTO pickup_operation_students (organization_id, operation_id, student_id, status, note, is_temporary, profile_pending, pickup_mode)
VALUES (?, ?, ?, 'planned', ?, ?, ?, ?)
`

type AddPickupOperationStudentParams struct {
	OrganizationID uint64 `json:"organization_id"`
	OperationID    uint64 `json:"operation_id"`
	StudentID      uint64 `json:"student_id"`
	Note           string `json:"note"`
	IsTemporary    bool   `json:"is_temporary"`
	ProfilePending bool   `json:"profile_pending"`
	PickupMode     string `json:"pickup_mode"`
}

func (q *Queries) AddPickupOperationStudent(ctx context.Context, arg AddPickupOperationStudentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addPickupOperationStudent,
		arg.OrganizationID,
		arg.OperationID,
		arg.StudentID,
		arg.Note,
		arg.IsTemporary,
		arg.ProfilePending,
		arg.PickupMode,
	)
}

const completePickupOperationStudentProfile = `-- name: CompletePickupOperationStudentProfile :execresult
UPDATE pickup_operation_students
SET profile_pending = FALSE, updated_at = CURRENT_TIMESTAMP(3)
WHERE operation_id = ? AND student_id = ? AND organization_id = ?
`

type CompletePickupOperationStudentProfileParams struct {
	OperationID    uint64 `json:"operation_id"`
	StudentID      uint64 `json:"student_id"`
	OrganizationID uint64 `json:"organization_id"`
}

func (q *Queries) CompletePickupOperationStudentProfile(ctx context.Context, arg CompletePickupOperationStudentProfileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, completePickupOperationStudentProfile, arg.OperationID, arg.StudentID, arg.OrganizationID)
}

const confirmPickupOperation = `-- name: ConfirmPickupOperation :execresult
UPDATE pickup_operations
SET status = 'confirmed', confirmed_at = ?, confirmed_by_user_id = ?, confirmed_by_name = ?,
    executing_teacher_user_id = ?, executing_teacher_name = ?, teacher_role = ?,
    expected_pickup_time = ?, notes = ?, updated_at = CURRENT_TIMESTAMP(3)
WHERE id = ? AND organization_id = ? AND status = 'draft'
`

type ConfirmPickupOperationParams struct {
	ConfirmedAt            sql.NullTime  `json:"confirmed_at"`
	ConfirmedByUserID      sql.NullInt64 `json:"confirmed_by_user_id"`
	ConfirmedByName        string        `json:"confirmed_by_name"`
	ExecutingTeacherUserID sql.NullInt64 `json:"executing_teacher_user_id"`
	ExecutingTeacherName   string        `json:"executing_teacher_name"`
	TeacherRole            string        `json:"teacher_role"`
	ExpectedPickupTime     string        `json:"expected_pickup_time"`
	Notes                  string        `json:"notes"`
	ID                     uint64        `json:"id"`
	OrganizationID         uint64        `json:"organization_id"`
}

func (q *Queries) ConfirmPickupOperation(ctx context.Context, arg ConfirmPickupOperationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, confirmPickupOperation,
		arg.ConfirmedAt,
		arg.ConfirmedByUserID,
		arg.ConfirmedByName,
		arg.ExecutingTeacherUserID,
		arg.ExecutingTeacherName,
		arg.TeacherRole,
		arg.ExpectedPickupTime,
		arg.Notes,
		arg.ID,
		arg.OrganizationID,
	)
}

const createNotification = `-- name: CreateNotification :execresult
INSERT INTO notifications (
    organization_id, student_id, operation_id, event_id, recipient_type,
    kind, title, content, status
) VALUES (?, ?, ?, ?, 'parent', ?, ?, ?, 'pending')
`

type CreateNotificationParams struct {
	OrganizationID uint64        `json:"organization_id"`
	StudentID      uint64        `json:"student_id"`
	OperationID    sql.NullInt64 `json:"operation_id"`
	EventID        sql.NullInt64 `json:"event_id"`
	Kind           string        `json:"kind"`
	Title          string        `json:"title"`
	Content        string        `json:"content"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNotification,
		arg.OrganizationID,
		arg.StudentID,
		arg.OperationID,
		arg.EventID,
		arg.Kind,
		arg.Title,
		arg.Content,
	)
}

const createPickupChangeRequest = `-- name: CreatePickupChangeRequest :execresult
INSERT INTO pickup_change_requests (
    organization_id, student_id, operation_id, change_date, requested_status,
    note, submitted_by, status
) VALUES (?, ?, ?, ?, ?, ?, ?, 'pending')
`

type CreatePickupChangeRequestParams struct {
	OrganizationID  uint64        `json:"organization_id"`
	StudentID       uint64        `json:"student_id"`
	OperationID     sql.NullInt64 `json:"operation_id"`
	ChangeDate      time.Time     `json:"change_date"`
	RequestedStatus string        `json:"requested_status"`
	Note            string        `json:"note"`
	SubmittedBy     string        `json:"submitted_by"`
}

func (q *Queries) CreatePickupChangeRequest(ctx context.Context, arg CreatePickupChangeRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPickupChangeRequest,
		arg.OrganizationID,
		arg.StudentID,
		arg.OperationID,
		arg.ChangeDate,
		arg.RequestedStatus,
		arg.Note,
		arg.SubmittedBy,
	)
}

const createPickupEvent = `-- name: CreatePickupEvent :execresult
INSERT INTO pickup_events (
    organization_id, operation_id, operation_student_id, student_id,
    event_type, event_at, operator_name, photo_url, note
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePickupEventParams struct {
	OrganizationID     uint64    `json:"organization_id"`
	OperationID        uint64    `json:"operation_id"`
	OperationStudentID uint64    `json:"operation_student_id"`
	StudentID          uint64    `json:"student_id"`
	EventType          string    `json:"event_type"`
	EventAt            time.Time `json:"event_at"`
	OperatorName       string    `json:"operator_name"`
	PhotoUrl           string    `json:"photo_url"`
	Note               string    `json:"note"`
}

func (q *Queries) CreatePickupEvent(ctx context.Context, arg CreatePickupEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPickupEvent,
		arg.OrganizationID,
		arg.OperationID,
		arg.OperationStudentID,
		arg.StudentID,
		arg.EventType,
		arg.EventAt,
		arg.OperatorName,
		arg.PhotoUrl,
		arg.Note,
	)
}

const createPickupOperation = `-- name: CreatePickupOperation :execresult
INSERT INTO pickup_operations (
    organization_id, operation_date, pickup_mode, school_id, school_class_id,
    care_class_id, teacher_user_id, teacher_name, status, notes
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'draft', ?)
`

type CreatePickupOperationParams struct {
	OrganizationID uint64        `json:"organization_id"`
	OperationDate  time.Time     `json:"operation_date"`
	PickupMode     string        `json:"pickup_mode"`
	SchoolID       uint64        `json:"school_id"`
	SchoolClassID  uint64        `json:"school_class_id"`
	CareClassID    sql.NullInt64 `json:"care_class_id"`
	TeacherUserID  sql.NullInt64 `json:"teacher_user_id"`
	TeacherName    string        `json:"teacher_name"`
	Notes          string        `json:"notes"`
}

func (q *Queries) CreatePickupOperation(ctx context.Context, arg CreatePickupOperationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPickupOperation,
		arg.OrganizationID,
		arg.OperationDate,
		arg.PickupMode,
		arg.SchoolID,
		arg.SchoolClassID,
		arg.CareClassID,
		arg.TeacherUserID,
		arg.TeacherName,
		arg.Notes,
	)
}

const createPickupOperationStudent = `-- name: CreatePickupOperationStudent :execresult
INSERT INTO pickup_operation_students (organization_id, operation_id, student_id, status)
VALUES (?, ?, ?, 'planned')
`

type CreatePickupOperationStudentParams struct {
	OrganizationID uint64 `json:"organization_id"`
	OperationID    uint64 `json:"operation_id"`
	StudentID      uint64 `json:"student_id"`
}

func (q *Queries) CreatePickupOperationStudent(ctx context.Context, arg CreatePickupOperationStudentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPickupOperationStudent, arg.OrganizationID, arg.OperationID, arg.StudentID)
}

const getPickupChangeRequest = `-- name: GetPickupChangeRequest :one
SELECT r.id, r.organization_id, r.student_id, s.name AS student_name, r.operation_id,
       r.change_date, r.requested_status, r.note, r.submitted_by, r.status,
       r.reviewed_by_user_id, r.reviewed_at, r.review_note, r.created_at, r.updated_at
FROM pickup_change_requests r
JOIN students s ON s.id = r.student_id
WHERE r.id = ? AND r.organization_id = ?
LIMIT 1
`

type GetPickupChangeRequestParams struct {
	ID             uint64 `json:"id"`
	OrganizationID uint64 `json:"organization_id"`
}

type GetPickupChangeRequestRow struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	StudentID        uint64        `json:"student_id"`
	StudentName      string        `json:"student_name"`
	OperationID      sql.NullInt64 `json:"operation_id"`
	ChangeDate       time.Time     `json:"change_date"`
	RequestedStatus  string        `json:"requested_status"`
	Note             string        `json:"note"`
	SubmittedBy      string        `json:"submitted_by"`
	Status           string        `json:"status"`
	ReviewedByUserID sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt       sql.NullTime  `json:"reviewed_at"`
	ReviewNote       string        `json:"review_note"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

func (q *Queries) GetPickupChangeRequest(ctx context.Context, arg GetPickupChangeRequestParams) (GetPickupChangeRequestRow, error) {
	row := q.db.QueryRowContext(ctx, getPickupChangeRequest, arg.ID, arg.OrganizationID)
	var i GetPickupChangeRequestRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StudentID,
		&i.StudentName,
		&i.OperationID,
		&i.ChangeDate,
		&i.RequestedStatus,
		&i.Note,
		&i.SubmittedBy,
		&i.Status,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPickupEventByID = `-- name: GetPickupEventByID :one
SELECT id, organization_id, operation_id, operation_student_id, student_id,
       event_type, event_at, operator_name, photo_url, note
FROM pickup_events
WHERE id = ? AND operation_id = ? AND organization_id = ?
LIMIT 1
`

type GetPickupEventByIDParams struct {
	ID             uint64 `json:"id"`
	OperationID    uint64 `json:"operation_id"`
	OrganizationID uint64 `json:"organization_id"`
}

func (q *Queries) GetPickupEventByID(ctx context.Context, arg GetPickupEventByIDParams) (PickupEvent, error) {
	row := q.db.QueryRowContext(ctx, getPickupEventByID, arg.ID, arg.OperationID, arg.OrganizationID)
	var i PickupEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OperationID,
		&i.OperationStudentID,
		&i.StudentID,
		&i.EventType,
		&i.EventAt,
		&i.OperatorName,
		&i.PhotoUrl,
		&i.Note,
	)
	return i, err
}

const getPickupOperationByID = `-- name: GetPickupOperationByID :one
SELECT id, organization_id, operation_date, pickup_mode, school_id, school_class_id,
       care_class_id, teacher_user_id, teacher_name, status, started_at, finished_at,
       notes, created_at, updated_at, confirmed_at, confirmed_by_user_id, confirmed_by_name,
       executing_teacher_user_id, executing_teacher_name, teacher_role, expected_pickup_time
FROM pickup_operations
WHERE id = ? AND organization_id = ?
LIMIT 1
`

type GetPickupOperationByIDParams struct {
	ID             uint64 `json:"id"`
	OrganizationID uint64 `json:"organization_id"`
}

func (q *Queries) GetPickupOperationByID(ctx context.Context, arg GetPickupOperationByIDParams) (PickupOperation, error) {
	row := q.db.QueryRowContext(ctx, getPickupOperationByID, arg.ID, arg.OrganizationID)
	var i PickupOperation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OperationDate,
		&i.PickupMode,
		&i.SchoolID,
		&i.SchoolClassID,
		&i.CareClassID,
		&i.TeacherUserID,
		&i.TeacherName,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedAt,
		&i.ConfirmedByUserID,
		&i.ConfirmedByName,
		&i.ExecutingTeacherUserID,
		&i.ExecutingTeacherName,
		&i.TeacherRole,
		&i.ExpectedPickupTime,
	)
	return i, err
}

const getPickupOperationStudent = `-- name: GetPickupOperationStudent :one
SELECT os.id AS operation_student_id, os.organization_id, os.operation_id, os.student_id,
       s.name AS student_name, os.status, os.photo_url, os.checked_at, os.note,
       os.created_at, os.updated_at, os.is_temporary, os.profile_pending, os.pickup_mode
FROM pickup_operation_students os
JOIN students s ON s.id = os.student_id
WHERE os.operation_id = ? AND os.student_id = ? AND os.organization_id = ?
LIMIT 1
`

type GetPickupOperationStudentParams struct {
	OperationID    uint64 `json:"operation_id"`
	StudentID      uint64 `json:"student_id"`
	OrganizationID uint64 `json:"organization_id"`
}

type GetPickupOperationStudentRow struct {
	OperationStudentID uint64       `json:"operation_student_id"`
	OrganizationID     uint64       `json:"organization_id"`
	OperationID        uint64       `json:"operation_id"`
	StudentID          uint64       `json:"student_id"`
	StudentName        string       `json:"student_name"`
	Status             string       `json:"status"`
	PhotoUrl           string       `json:"photo_url"`
	CheckedAt          sql.NullTime `json:"checked_at"`
	Note               string       `json:"note"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          time.Time    `json:"updated_at"`
	IsTemporary        bool         `json:"is_temporary"`
	ProfilePending     bool         `json:"profile_pending"`
	PickupMode         string       `json:"pickup_mode"`
}

func (q *Queries) GetPickupOperationStudent(ctx context.Context, arg GetPickupOperationStudentParams) (GetPickupOperationStudentRow, error) {
	row := q.db.QueryRowContext(ctx, getPickupOperationStudent, arg.OperationID, arg.StudentID, arg.OrganizationID)
	var i GetPickupOperationStudentRow
	err := row.Scan(
		&i.OperationStudentID,
		&i.OrganizationID,
		&i.OperationID,
		&i.StudentID,
		&i.StudentName,
		&i.Status,
		&i.PhotoUrl,
		&i.CheckedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsTemporary,
		&i.ProfilePending,
		&i.PickupMode,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, organization_id, student_id, operation_id, event_id, recipient_type,
       kind, title, content, status, sent_at, delivery_attempts, last_attempt_at,
       delivery_error, next_retry_at, created_at, read_at
FROM notifications
WHERE organization_id = ?
ORDER BY created_at DESC, id DESC
`

type ListNotificationsRow struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	StudentID        uint64        `json:"student_id"`
	OperationID      sql.NullInt64 `json:"operation_id"`
	EventID          sql.NullInt64 `json:"event_id"`
	RecipientType    string        `json:"recipient_type"`
	Kind             string        `json:"kind"`
	Title            string        `json:"title"`
	Content          string        `json:"content"`
	Status           string        `json:"status"`
	SentAt           sql.NullTime  `json:"sent_at"`
	DeliveryAttempts uint32        `json:"delivery_attempts"`
	LastAttemptAt    sql.NullTime  `json:"last_attempt_at"`
	DeliveryError    string        `json:"delivery_error"`
	NextRetryAt      sql.NullTime  `json:"next_retry_at"`
	CreatedAt        time.Time     `json:"created_at"`
	ReadAt           sql.NullTime  `json:"read_at"`
}

func (q *Queries) ListNotifications(ctx context.Context, organizationID uint64) ([]ListNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StudentID,
			&i.OperationID,
			&i.EventID,
			&i.RecipientType,
			&i.Kind,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.SentAt,
			&i.DeliveryAttempts,
			&i.LastAttemptAt,
			&i.DeliveryError,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPickupChangeRequests = `-- name: ListPickupChangeRequests :many
SELECT r.id, r.organization_id, r.student_id, s.name AS student_name, r.operation_id,
       r.change_date, r.requested_status, r.note, r.submitted_by, r.status,
       r.reviewed_by_user_id, r.reviewed_at, r.review_note, r.created_at, r.updated_at
FROM pickup_change_requests r
JOIN students s ON s.id = r.student_id
WHERE r.organization_id = ?
ORDER BY r.change_date DESC, r.created_at DESC, r.id DESC
`

type ListPickupChangeRequestsRow struct {
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
	StudentID        uint64        `json:"student_id"`
	StudentName      string        `json:"student_name"`
	OperationID      sql.NullInt64 `json:"operation_id"`
	ChangeDate       time.Time     `json:"change_date"`
	RequestedStatus  string        `json:"requested_status"`
	Note             string        `json:"note"`
	SubmittedBy      string        `json:"submitted_by"`
	Status           string        `json:"status"`
	ReviewedByUserID sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt       sql.NullTime  `json:"reviewed_at"`
	ReviewNote       string        `json:"review_note"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

func (q *Queries) ListPickupChangeRequests(ctx context.Context, organizationID uint64) ([]ListPickupChangeRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPickupChangeRequests, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPickupChangeRequestsRow{}
	for rows.Next() {
		var i ListPickupChangeRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StudentID,
			&i.StudentName,
			&i.OperationID,
			&i.ChangeDate,
			&i.RequestedStatus,
			&i.Note,
			&i.SubmittedBy,
			&i.Status,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.ReviewNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPickupEvents = `-- name: ListPickupEvents :many
SELECT id, organization_id, operation_id, operation_student_id, student_id,
       event_type, event_at, operator_name, photo_url, note
FROM pickup_events
WHERE operation_id = ? AND organization_id = ?
ORDER BY event_at DESC, id DESC
`

type ListPickupEventsParams struct {
	OperationID    uint64 `json:"operation_id"`
	OrganizationID uint64 `json:"organization_id"`
}

func (q *Queries) ListPickupEvents(ctx context.Context, arg ListPickupEventsParams) ([]PickupEvent, error) {
	rows, err := q.db.QueryContext(ctx, listPickupEvents, arg.OperationID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PickupEvent{}
	for rows.Next() {
		var i PickupEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OperationID,
			&i.OperationStudentID,
			&i.StudentID,
			&i.EventType,
			&i.EventAt,
			&i.OperatorName,
			&i.PhotoUrl,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPickupOperationStudents = `-- name: ListPickupOperationStudents :many
SELECT os.id AS operation_student_id, os.organization_id, os.operation_id, os.student_id,
       s.name AS student_name, os.status, os.photo_url, os.checked_at, os.note,
       os.created_at, os.updated_at, os.is_temporary, os.profile_pending, os.pickup_mode
FROM pickup_operation_students os
JOIN students s ON s.id = os.student_id
WHERE os.operation_id = ? AND os.organization_id = ?
ORDER BY s.name, os.student_id
`

type ListPickupOperationStudentsParams struct {
	OperationID    uint64 `json:"operation_id"`
	OrganizationID uint64 `json:"organization_id"`
}

type ListPickupOperationStudentsRow struct {
	OperationStudentID uint64       `json:"operation_student_id"`
	OrganizationID     uint64       `json:"organization_id"`
	OperationID        uint64       `json:"operation_id"`
	StudentID          uint64       `json:"student_id"`
	StudentName        string       `json:"student_name"`
	Status             string       `json:"status"`
	PhotoUrl           string       `json:"photo_url"`
	CheckedAt          sql.NullTime `json:"checked_at"`
	Note               string       `json:"note"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          time.Time    `json:"updated_at"`
	IsTemporary        bool         `json:"is_temporary"`
	ProfilePending     bool         `json:"profile_pending"`
	PickupMode         string       `json:"pickup_mode"`
}

func (q *Queries) ListPickupOperationStudents(ctx context.Context, arg ListPickupOperationStudentsParams) ([]ListPickupOperationStudentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPickupOperationStudents, arg.OperationID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPickupOperationStudentsRow{}
	for rows.Next() {
		var i ListPickupOperationStudentsRow
		if err := rows.Scan(
			&i.OperationStudentID,
			&i.OrganizationID,
			&i.OperationID,
			&i.StudentID,
			&i.StudentName,
			&i.Status,
			&i.PhotoUrl,
			&i.CheckedAt,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsTemporary,
			&i.ProfilePending,
			&i.PickupMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPickupOperations = `-- name: ListPickupOperations :many
SELECT id, organization_id, operation_date, pickup_mode, school_id, school_class_id,
       care_class_id, teacher_user_id, teacher_name, status, started_at, finished_at,
       notes, created_at, updated_at, confirmed_at, confirmed_by_user_id, confirmed_by_name,
       executing_teacher_user_id, executing_teacher_name, teacher_role, expected_pickup_time
FROM pickup_operations
WHERE organization_id = ?
ORDER BY operation_date DESC, id DESC
`

func (q *Queries) ListPickupOperations(ctx context.Context, organizationID uint64) ([]PickupOperation, error) {
	rows, err := q.db.QueryContext(ctx, listPickupOperations, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PickupOperation{}
	for rows.Next() {
		var i PickupOperation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OperationDate,
			&i.PickupMode,
			&i.SchoolID,
			&i.SchoolClassID,
			&i.CareClassID,
			&i.TeacherUserID,
			&i.TeacherName,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConfirmedAt,
			&i.ConfirmedByUserID,
			&i.ConfirmedByName,
			&i.ExecutingTeacherUserID,
			&i.ExecutingTeacherName,
			&i.TeacherRole,
			&i.ExpectedPickupTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execresult
UPDATE notifications
SET read_at = COALESCE(read_at, CURRENT_TIMESTAMP(3))
WHERE id = ? AND organization_id = ?
`

type MarkNotificationReadParams struct {
	ID             uint64 `json:"id"`
	OrganizationID uint64 `json:"organization_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markNotificationRead, arg.ID, arg.OrganizationID)
}

const reviewPickupChangeRequest = `-- name: ReviewPickupChangeRequest :execresult
UPDATE pickup_change_requests
SET status = ?, reviewed_by_user_id = ?, reviewed_at = ?, review_note = ?, updated_at = CURRENT_TIMESTAMP(3)
WHERE id = ? AND organization_id = ? AND status = 'pending'
`

type ReviewPickupChangeRequestParams struct {
	Status           string        `json:"status"`
	ReviewedByUserID sql.NullInt64 `json:"reviewed_by_user_id"`
	ReviewedAt       sql.NullTime  `json:"reviewed_at"`
	ReviewNote       string        `json:"review_note"`
	ID               uint64        `json:"id"`
	OrganizationID   uint64        `json:"organization_id"`
}

func (q *Queries) ReviewPickupChangeRequest(ctx context.Context, arg ReviewPickupChangeRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, reviewPickupChangeRequest,
		arg.Status,
		arg.ReviewedByUserID,
		arg.ReviewedAt,
		arg.ReviewNote,
		arg.ID,
		arg.OrganizationID,
	)
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :execresult
UPDATE notifications
SET status = ?, sent_at = ?, delivery_attempts = ?, last_attempt_at = ?,
    delivery_error = ?, next_retry_at = ?
WHERE id = ? AND organization_id = ?
`

type UpdateNotificationStatusParams struct {
	Status           string       `json:"status"`
	SentAt           sql.NullTime `json:"sent_at"`
	DeliveryAttempts uint32       `json:"delivery_attempts"`
	LastAttemptAt    sql.NullTime `json:"last_attempt_at"`
	DeliveryError    string       `json:"delivery_error"`
	NextRetryAt      sql.NullTime `json:"next_retry_at"`
	ID               uint64       `json:"id"`
	OrganizationID   uint64       `json:"organization_id"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateNotificationStatus,
		arg.Status,
		arg.SentAt,
		arg.DeliveryAttempts,
		arg.LastAttemptAt,
		arg.DeliveryError,
		arg.NextRetryAt,
		arg.ID,
		arg.OrganizationID,
	)
}

const updatePickupOperationStatus = `-- name: UpdatePickupOperationStatus :execresult
UPDATE pickup_operations
SET status = ?, started_at = COALESCE(?, started_at), finished_at = COALESCE(?, finished_at)
WHERE id = ? AND organization_id = ?
`

type UpdatePickupOperationStatusParams struct {
	Status         string       `json:"status"`
	StartedAt      sql.NullTime `json:"started_at"`
	FinishedAt     sql.NullTime `json:"finished_at"`
	ID             uint64       `json:"id"`
	OrganizationID uint64       `json:"organization_id"`
}

func (q *Queries) UpdatePickupOperationStatus(ctx context.Context, arg UpdatePickupOperationStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePickupOperationStatus,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
		arg.OrganizationID,
	)
}

const updatePickupOperationStudent = `-- name: UpdatePickupOperationStudent :execresult
UPDATE pickup_operation_students
SET status = ?, photo_url = ?, checked_at = ?, note = ?
WHERE operation_id = ? AND student_id = ? AND organization_id = ?
`

type UpdatePickupOperationStudentParams struct {
	Status         string       `json:"status"`
	PhotoUrl       string       `json:"photo_url"`
	CheckedAt      sql.NullTime `json:"checked_at"`
	Note           string       `json:"note"`
	OperationID    uint64       `json:"operation_id"`
	StudentID      uint64       `json:"student_id"`
	OrganizationID uint64       `json:"organization_id"`
}

func (q *Queries) UpdatePickupOperationStudent(ctx context.Context, arg UpdatePickupOperationStudentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePickupOperationStudent,
		arg.Status,
		arg.PhotoUrl,
		arg.CheckedAt,
		arg.Note,
		arg.OperationID,
		arg.StudentID,
		arg.OrganizationID,
	)
}
