// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_admin.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const consumeOrganizationInvite = `-- name: ConsumeOrganizationInvite :execresult
UPDATE organization_invites
SET used_count = used_count + 1,
    status = CASE WHEN used_count + 1 >= max_uses THEN 'exhausted' ELSE 'active' END
WHERE id = ? AND status = 'active' AND used_count < max_uses
  AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP(3))
`

func (q *Queries) ConsumeOrganizationInvite(ctx context.Context, id uint64) (sql.Result, error) {
	return q.db.ExecContext(ctx, consumeOrganizationInvite, id)
}

const createOrganization = `-- name: CreateOrganization :execresult
INSERT INTO organizations (name, slug, contact_name, contact_phone, authorized_until, status)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateOrganizationParams struct {
	Name            string       `json:"name"`
	Slug            string       `json:"slug"`
	ContactName     string       `json:"contact_name"`
	ContactPhone    string       `json:"contact_phone"`
	AuthorizedUntil sql.NullTime `json:"authorized_until"`
	Status          string       `json:"status"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrganization,
		arg.Name,
		arg.Slug,
		arg.ContactName,
		arg.ContactPhone,
		arg.AuthorizedUntil,
		arg.Status,
	)
}

const createOrganizationInvite = `-- name: CreateOrganizationInvite :execresult
INSERT INTO organization_invites (code_hash, code_hint, max_uses, expires_at, status, note, created_by_user_id)
VALUES (?, ?, ?, ?, 'active', ?, ?)
`

type CreateOrganizationInviteParams struct {
	CodeHash        string       `json:"code_hash"`
	CodeHint        string       `json:"code_hint"`
	MaxUses         uint32       `json:"max_uses"`
	ExpiresAt       sql.NullTime `json:"expires_at"`
	Note            string       `json:"note"`
	CreatedByUserID uint64       `json:"created_by_user_id"`
}

func (q *Queries) CreateOrganizationInvite(ctx context.Context, arg CreateOrganizationInviteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrganizationInvite,
		arg.CodeHash,
		arg.CodeHint,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.Note,
		arg.CreatedByUserID,
	)
}

const createOrganizationRegistration = `-- name: CreateOrganizationRegistration :execresult
INSERT INTO organization_registrations (invite_id, organization_name, slug, contact_name, contact_phone, admin_username, admin_password_hash, status)
VALUES (?, ?, ?, ?, ?, ?, ?, 'pending')
`

type CreateOrganizationRegistrationParams struct {
	InviteID          uint64 `json:"invite_id"`
	OrganizationName  string `json:"organization_name"`
	Slug              string `json:"slug"`
	ContactName       string `json:"contact_name"`
	ContactPhone      string `json:"contact_phone"`
	AdminUsername     string `json:"admin_username"`
	AdminPasswordHash string `json:"admin_password_hash"`
}

func (q *Queries) CreateOrganizationRegistration(ctx context.Context, arg CreateOrganizationRegistrationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrganizationRegistration,
		arg.InviteID,
		arg.OrganizationName,
		arg.Slug,
		arg.ContactName,
		arg.ContactPhone,
		arg.AdminUsername,
		arg.AdminPasswordHash,
	)
}

const getOrganizationInviteByHash = `-- name: GetOrganizationInviteByHash :one
SELECT id, code_hash, code_hint, max_uses, used_count, expires_at, status, note, created_by_user_id, created_at, updated_at
FROM organization_invites
WHERE code_hash = ?
LIMIT 1
`

func (q *Queries) GetOrganizationInviteByHash(ctx context.Context, codeHash string) (OrganizationInvite, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationInviteByHash, codeHash)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.CodeHint,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.Status,
		&i.Note,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationRegistration = `-- name: GetOrganizationRegistration :one
SELECT id, invite_id, organization_id, organization_name, slug, contact_name, contact_phone, admin_username, admin_password_hash, status, review_note, reviewed_by_user_id, reviewed_at, created_at, updated_at
FROM organization_registrations
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetOrganizationRegistration(ctx context.Context, id uint64) (OrganizationRegistration, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationRegistration, id)
	var i OrganizationRegistration
	err := row.Scan(
		&i.ID,
		&i.InviteID,
		&i.OrganizationID,
		&i.OrganizationName,
		&i.Slug,
		&i.ContactName,
		&i.ContactPhone,
		&i.AdminUsername,
		&i.AdminPasswordHash,
		&i.Status,
		&i.ReviewNote,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationInvites = `-- name: ListOrganizationInvites :many
SELECT id, code_hash, code_hint, max_uses, used_count, expires_at, status, note, created_by_user_id, created_at, updated_at
FROM organization_invites
WHERE (? IS NULL OR status = ?)
ORDER BY id DESC
`

type ListOrganizationInvitesParams struct {
	StatusFilter sql.NullString `json:"status_filter"`
}

func (q *Queries) ListOrganizationInvites(ctx context.Context, arg ListOrganizationInvitesParams) ([]OrganizationInvite, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationInvites, arg.StatusFilter, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationInvite{}
	for rows.Next() {
		var i OrganizationInvite
		if err := rows.Scan(
			&i.ID,
			&i.CodeHash,
			&i.CodeHint,
			&i.MaxUses,
			&i.UsedCount,
			&i.ExpiresAt,
			&i.Status,
			&i.Note,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationRegistrations = `-- name: ListOrganizationRegistrations :many
SELECT id, invite_id, organization_id, organization_name, slug, contact_name, contact_phone, admin_username, admin_password_hash, status, review_note, reviewed_by_user_id, reviewed_at, created_at, updated_at
FROM organization_registrations
WHERE (? IS NULL OR status = ?)
ORDER BY id DESC
`

type ListOrganizationRegistrationsParams struct {
	StatusFilter sql.NullString `json:"status_filter"`
}

func (q *Queries) ListOrganizationRegistrations(ctx context.Context, arg ListOrganizationRegistrationsParams) ([]OrganizationRegistration, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationRegistrations, arg.StatusFilter, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationRegistration{}
	for rows.Next() {
		var i OrganizationRegistration
		if err := rows.Scan(
			&i.ID,
			&i.InviteID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.Slug,
			&i.ContactName,
			&i.ContactPhone,
			&i.AdminUsername,
			&i.AdminPasswordHash,
			&i.Status,
			&i.ReviewNote,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, slug, contact_name, contact_phone, authorized_until, status, created_at, updated_at
FROM organizations
ORDER BY id ASC
`

type ListOrganizationsRow struct {
	ID              uint64       `json:"id"`
	Name            string       `json:"name"`
	Slug            string       `json:"slug"`
	ContactName     string       `json:"contact_name"`
	ContactPhone    string       `json:"contact_phone"`
	AuthorizedUntil sql.NullTime `json:"authorized_until"`
	Status          string       `json:"status"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

func (q *Queries) ListOrganizations(ctx context.Context) ([]ListOrganizationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsRow{}
	for rows.Next() {
		var i ListOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ContactName,
			&i.ContactPhone,
			&i.AuthorizedUntil,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOrganizationInvite = `-- name: RevokeOrganizationInvite :execresult
UPDATE organization_invites SET status = 'revoked' WHERE id = ? AND status = 'active'
`

func (q *Queries) RevokeOrganizationInvite(ctx context.Context, id uint64) (sql.Result, error) {
	return q.db.ExecContext(ctx, revokeOrganizationInvite, id)
}

const setOrganizationRegistrationStatus = `-- name: SetOrganizationRegistrationStatus :execresult
UPDATE organization_registrations
SET status = ?, organization_id = ?, review_note = ?, reviewed_by_user_id = ?, reviewed_at = CURRENT_TIMESTAMP(3)
WHERE id = ? AND status = 'pending'
`

type SetOrganizationRegistrationStatusParams struct {
	Status           string        `json:"status"`
	OrganizationID   sql.NullInt64 `json:"organization_id"`
	ReviewNote       string        `json:"review_note"`
	ReviewedByUserID sql.NullInt64 `json:"reviewed_by_user_id"`
	ID               uint64        `json:"id"`
}

func (q *Queries) SetOrganizationRegistrationStatus(ctx context.Context, arg SetOrganizationRegistrationStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setOrganizationRegistrationStatus,
		arg.Status,
		arg.OrganizationID,
		arg.ReviewNote,
		arg.ReviewedByUserID,
		arg.ID,
	)
}

const setOrganizationStatus = `-- name: SetOrganizationStatus :execresult
UPDATE organizations SET status = ? WHERE id = ?
`

type SetOrganizationStatusParams struct {
	Status string `json:"status"`
	ID     uint64 `json:"id"`
}

func (q *Queries) SetOrganizationStatus(ctx context.Context, arg SetOrganizationStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setOrganizationStatus, arg.Status, arg.ID)
}
