// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teacher_class_assignments.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTeacherClassAssignment = `-- name: CreateTeacherClassAssignment :execresult
INSERT INTO teacher_class_assignments (
    organization_id, teacher_user_id, school_class_id, status
) VALUES (?, ?, ?, 'active')
`

type CreateTeacherClassAssignmentParams struct {
	OrganizationID uint64 `json:"organization_id"`
	TeacherUserID  uint64 `json:"teacher_user_id"`
	SchoolClassID  uint64 `json:"school_class_id"`
}

func (q *Queries) CreateTeacherClassAssignment(ctx context.Context, arg CreateTeacherClassAssignmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTeacherClassAssignment, arg.OrganizationID, arg.TeacherUserID, arg.SchoolClassID)
}

const getTeacherClassAssignment = `-- name: GetTeacherClassAssignment :one
SELECT id, organization_id, teacher_user_id, school_class_id,
       status, created_at, updated_at
FROM teacher_class_assignments
WHERE id = ? AND organization_id = ?
LIMIT 1
`

type GetTeacherClassAssignmentParams struct {
	ID             uint64 `json:"id"`
	OrganizationID uint64 `json:"organization_id"`
}

func (q *Queries) GetTeacherClassAssignment(ctx context.Context, arg GetTeacherClassAssignmentParams) (TeacherClassAssignment, error) {
	row := q.db.QueryRowContext(ctx, getTeacherClassAssignment, arg.ID, arg.OrganizationID)
	var i TeacherClassAssignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeacherUserID,
		&i.SchoolClassID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeacherClassAssignmentByPair = `-- name: GetTeacherClassAssignmentByPair :one
SELECT id, organization_id, teacher_user_id, school_class_id,
       status, created_at, updated_at
FROM teacher_class_assignments
WHERE organization_id = ? AND teacher_user_id = ? AND school_class_id = ?
LIMIT 1
`

type GetTeacherClassAssignmentByPairParams struct {
	OrganizationID uint64 `json:"organization_id"`
	TeacherUserID  uint64 `json:"teacher_user_id"`
	SchoolClassID  uint64 `json:"school_class_id"`
}

func (q *Queries) GetTeacherClassAssignmentByPair(ctx context.Context, arg GetTeacherClassAssignmentByPairParams) (TeacherClassAssignment, error) {
	row := q.db.QueryRowContext(ctx, getTeacherClassAssignmentByPair, arg.OrganizationID, arg.TeacherUserID, arg.SchoolClassID)
	var i TeacherClassAssignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeacherUserID,
		&i.SchoolClassID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeacherClassAssignments = `-- name: ListTeacherClassAssignments :many
SELECT a.id, a.organization_id, a.teacher_user_id, a.school_class_id,
       a.status, a.created_at, a.updated_at
FROM teacher_class_assignments a
WHERE a.organization_id = ?
  AND (? = 0 OR a.teacher_user_id = ?)
  AND (? = 0 OR a.school_class_id = ?)
ORDER BY a.status, a.id DESC
`

type ListTeacherClassAssignmentsParams struct {
	OrganizationID uint64 `json:"organization_id"`
	TeacherUserID  uint64 `json:"teacher_user_id"`
	SchoolClassID  uint64 `json:"school_class_id"`
}

func (q *Queries) ListTeacherClassAssignments(ctx context.Context, arg ListTeacherClassAssignmentsParams) ([]TeacherClassAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listTeacherClassAssignments,
		arg.OrganizationID,
		arg.TeacherUserID,
		arg.TeacherUserID,
		arg.SchoolClassID,
		arg.SchoolClassID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeacherClassAssignment{}
	for rows.Next() {
		var i TeacherClassAssignment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TeacherUserID,
			&i.SchoolClassID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTeacherClassAssignmentStatus = `-- name: SetTeacherClassAssignmentStatus :execresult
UPDATE teacher_class_assignments
SET status = ?
WHERE id = ? AND organization_id = ?
`

type SetTeacherClassAssignmentStatusParams struct {
	Status         string `json:"status"`
	ID             uint64 `json:"id"`
	OrganizationID uint64 `json:"organization_id"`
}

func (q *Queries) SetTeacherClassAssignmentStatus(ctx context.Context, arg SetTeacherClassAssignmentStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setTeacherClassAssignmentStatus, arg.Status, arg.ID, arg.OrganizationID)
}
