// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
    username,
    password_hash,
    role,
    nickname,
    avatar,
    status
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	Nickname     string `json:"nickname"`
	Avatar       string `json:"avatar"`
	Status       string `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Nickname,
		arg.Avatar,
		arg.Status,
	)
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    username,
    password_hash,
    role,
    nickname,
    avatar,
    status,
    created_at,
    updated_at
FROM users
WHERE id = ?
LIMIT 1
`

type GetUserByIDRow struct {
	ID           uint64    `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	Nickname     string    `json:"nickname"`
	Avatar       string    `json:"avatar"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uint64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Nickname,
		&i.Avatar,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    id,
    username,
    password_hash,
    role,
    nickname,
    avatar,
    status,
    created_at,
    updated_at
FROM users
WHERE username = ?
LIMIT 1
`

type GetUserByUsernameRow struct {
	ID           uint64    `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	Nickname     string    `json:"nickname"`
	Avatar       string    `json:"avatar"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Nickname,
		&i.Avatar,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    username,
    password_hash,
    role,
    nickname,
    avatar,
    status,
    created_at,
    updated_at
FROM users
ORDER BY id ASC
`

type ListUsersRow struct {
	ID           uint64    `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	Nickname     string    `json:"nickname"`
	Avatar       string    `json:"avatar"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.Nickname,
			&i.Avatar,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserStatus = `-- name: SetUserStatus :execresult
UPDATE users
SET status = ?
WHERE id = ?
`

type SetUserStatusParams struct {
	Status string `json:"status"`
	ID     uint64 `json:"id"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setUserStatus, arg.Status, arg.ID)
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE users
SET
	password_hash = ?,
	role = ?,
	nickname = ?,
	avatar = ?,
	status = ?
WHERE id = ?
`

type UpdateUserParams struct {
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	Nickname     string `json:"nickname"`
	Avatar       string `json:"avatar"`
	Status       string `json:"status"`
	ID           uint64 `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser,
		arg.PasswordHash,
		arg.Role,
		arg.Nickname,
		arg.Avatar,
		arg.Status,
		arg.ID,
	)
}

const updateUserProfile = `-- name: UpdateUserProfile :execresult
UPDATE users
SET
	nickname = ?,
	avatar = ?
WHERE id = ?
`

type UpdateUserProfileParams struct {
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	ID       uint64 `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserProfile, arg.Nickname, arg.Avatar, arg.ID)
}
